-- Seed file for social media database
-- This seed respects all triggers and constraints
-- Uses user IDs 1-10 only

BEGIN;

------------------------------------------
-- POSTS
------------------------------------------
-- Note: IDs are auto-generated by master_index trigger
-- Personal posts (audience: everyone)
INSERT INTO posts (post_body, creator_id, group_id, audience) VALUES
('Just finished reading an amazing book on PostgreSQL triggers! 📚', 1, NULL, 'everyone'),
('Beautiful sunset today at the beach 🌅', 2, NULL, 'everyone'),
('Who else is excited for the weekend?', 3, NULL, 'everyone'),
('My new coding project is finally coming together!', 4, NULL, 'everyone'),
('Coffee and code - the perfect combination ☕💻', 5, NULL, 'everyone');

-- Posts for followers only
INSERT INTO posts (post_body, creator_id, group_id, audience) VALUES
('Sharing some personal news with my close friends...', 6, NULL, 'followers'),
('Working on something special, details coming soon!', 7, NULL, 'followers');

-- Group posts
INSERT INTO posts (post_body, creator_id, group_id, audience) VALUES
('Welcome to our book club! What should we read next?', 1, 100, 'group'),
('Great meeting today team! Here are the action items...', 2, 101, 'group'),
('Reminder: Project deadline is next Friday', 3, 101, 'group'),
('Check out this article about design patterns', 4, 102, 'group'),
('Group hiking trip planned for next month! 🥾', 5, 103, 'group');

-- Selected audience posts
INSERT INTO posts (post_body, creator_id, group_id, audience) VALUES
('Hey selected friends, planning a surprise party!', 8, NULL, 'selected'),
('Private update for specific people only', 9, NULL, 'selected');

-- Get the IDs of the selected audience posts for post_audience table
DO $$
DECLARE
    selected_post_1 BIGINT;
    selected_post_2 BIGINT;
BEGIN
    SELECT id INTO selected_post_1 FROM posts WHERE creator_id = 8 AND audience = 'selected' LIMIT 1;
    SELECT id INTO selected_post_2 FROM posts WHERE creator_id = 9 AND audience = 'selected' LIMIT 1;
    
    -- Add allowed users for selected posts
    INSERT INTO post_audience (post_id, allowed_user_id) VALUES
    (selected_post_1, 1),
    (selected_post_1, 2),
    (selected_post_1, 3),
    (selected_post_2, 4),
    (selected_post_2, 5),
    (selected_post_2, 6);
END $$;

-- More varied posts
INSERT INTO posts (post_body, creator_id, group_id, audience) VALUES
('Does anyone have recommendations for project management tools?', 10, NULL, 'everyone'),
('Just deployed my first production app! 🚀', 1, NULL, 'everyone'),
('Learning React has been such a journey', 2, NULL, 'everyone'),
('Why do we fall? So we can learn to pick ourselves up.', 3, NULL, 'everyone'),
('Database optimization is an art form', 4, NULL, 'everyone'),
('Team lunch tomorrow at 12:30!', 5, 101, 'group');

------------------------------------------
-- COMMENTS
------------------------------------------
DO $$
DECLARE
    post_ids BIGINT[];
BEGIN
    -- Get all post IDs in order
    SELECT ARRAY_AGG(id ORDER BY created_at) INTO post_ids FROM posts;
    
    -- Comments on first post (PostgreSQL book post)
    INSERT INTO comments (comment_creator_id, parent_id, comment_body) VALUES
    (2, post_ids[1], 'What book was it? I''m always looking for good database resources!'),
    (3, post_ids[1], 'Triggers can be tricky but so powerful when used right'),
    (1, post_ids[1], 'It was "PostgreSQL: Up and Running" - highly recommend!');

    -- Comments on second post (sunset post)
    INSERT INTO comments (comment_creator_id, parent_id, comment_body) VALUES
    (1, post_ids[2], 'Gorgeous! Which beach?'),
    (4, post_ids[2], 'I love sunset photography 📸'),
    (2, post_ids[2], 'Thanks everyone! This was at Santa Monica');

    -- Comments on third post (weekend post)
    INSERT INTO comments (comment_creator_id, parent_id, comment_body) VALUES
    (5, post_ids[3], 'Me! Planning to catch up on some reading'),
    (6, post_ids[3], 'Going hiking with friends!'),
    (7, post_ids[3], 'Just relaxing at home 😊');

    -- Comments on fourth post (coding project)
    INSERT INTO comments (comment_creator_id, parent_id, comment_body) VALUES
    (8, post_ids[4], 'What tech stack are you using?'),
    (4, post_ids[4], 'Node.js backend with React frontend!'),
    (9, post_ids[4], 'Nice! Let me know if you need any help');

    -- Comments on fifth post (coffee and code)
    INSERT INTO comments (comment_creator_id, parent_id, comment_body) VALUES
    (10, post_ids[5], 'The only way to start the day!'),
    (1, post_ids[5], 'Agreed! What are you working on?');

    -- Comments on group posts
    INSERT INTO comments (comment_creator_id, parent_id, comment_body) VALUES
    (2, post_ids[8], 'How about "Clean Code" by Robert Martin?'),
    (3, post_ids[8], 'Or we could try a sci-fi novel for variety'),
    (5, post_ids[9], 'Got it, will have my part done by Wednesday'),
    (6, post_ids[10], 'Thanks for the reminder!');

    -- More comments on popular posts
    INSERT INTO comments (comment_creator_id, parent_id, comment_body) VALUES
    (7, post_ids[16], 'Congratulations! What kind of app is it?'),
    (8, post_ids[16], 'That''s awesome! How long did it take?'),
    (1, post_ids[16], 'Thanks! It''s a task management app. Took about 3 months'),
    (9, post_ids[17], 'Same here! The hooks really changed everything'),
    (10, post_ids[19], 'So true! Indexes make all the difference');
END $$;

------------------------------------------
-- EVENTS
------------------------------------------
INSERT INTO events (event_title, event_body, event_creator_id, group_id, event_date) VALUES
('Book Club Meeting', 'Monthly book club discussion. This month: "The Pragmatic Programmer"', 1, 100, '2025-01-15'),
('Team Building Workshop', 'Fun team activities and lunch provided!', 2, 101, '2025-01-20'),
('Tech Talk: Database Optimization', 'Learn about indexing strategies and query optimization', 4, 102, '2025-01-25'),
('Hiking Trip - Mountain Peak Trail', 'Moderate difficulty, 8 miles round trip. Bring water and snacks!', 5, 103, '2025-02-01'),
('Code Review Session', 'Weekly code review and best practices discussion', 3, 101, '2025-01-18'),
('Annual Company Picnic', 'Food, games, and fun for everyone! Families welcome.', 6, 104, '2025-02-15'),
('Webinar: Modern React Patterns', 'Online webinar covering latest React best practices', 7, 102, '2025-01-22');

------------------------------------------
-- EVENT RESPONSES
------------------------------------------
DO $$
DECLARE
    event_ids BIGINT[];
BEGIN
    -- Get all event IDs in order
    SELECT ARRAY_AGG(id ORDER BY created_at) INTO event_ids FROM events;
    
    -- Event 1 (Book Club)
    INSERT INTO event_responses (event_id, user_id, going) VALUES
    (event_ids[1], 1, true),
    (event_ids[1], 2, true),
    (event_ids[1], 3, false),
    (event_ids[1], 4, true),
    (event_ids[1], 5, true);

    -- Event 2 (Team Building)
    INSERT INTO event_responses (event_id, user_id, going) VALUES
    (event_ids[2], 2, true),
    (event_ids[2], 3, true),
    (event_ids[2], 5, true),
    (event_ids[2], 6, false),
    (event_ids[2], 7, true),
    (event_ids[2], 8, true);

    -- Event 3 (Tech Talk)
    INSERT INTO event_responses (event_id, user_id, going) VALUES
    (event_ids[3], 1, true),
    (event_ids[3], 4, true),
    (event_ids[3], 8, true),
    (event_ids[3], 9, true),
    (event_ids[3], 10, false);

    -- Event 4 (Hiking)
    INSERT INTO event_responses (event_id, user_id, going) VALUES
    (event_ids[4], 5, true),
    (event_ids[4], 6, true),
    (event_ids[4], 7, true),
    (event_ids[4], 9, false),
    (event_ids[4], 10, true);

    -- Event 5 (Code Review)
    INSERT INTO event_responses (event_id, user_id, going) VALUES
    (event_ids[5], 2, true),
    (event_ids[5], 3, true),
    (event_ids[5], 5, true),
    (event_ids[5], 8, false);

    -- Event 6 (Company Picnic)
    INSERT INTO event_responses (event_id, user_id, going) VALUES
    (event_ids[6], 1, true),
    (event_ids[6], 2, true),
    (event_ids[6], 3, true),
    (event_ids[6], 4, true),
    (event_ids[6], 6, true),
    (event_ids[6], 7, true),
    (event_ids[6], 8, false),
    (event_ids[6], 9, true),
    (event_ids[6], 10, true);

    -- Event 7 (Webinar)
    INSERT INTO event_responses (event_id, user_id, going) VALUES
    (event_ids[7], 4, true),
    (event_ids[7], 7, true),
    (event_ids[7], 9, true);
END $$;

------------------------------------------
-- REACTIONS (Likes)
------------------------------------------
DO $$
DECLARE
    post_ids BIGINT[];
    comment_ids BIGINT[];
BEGIN
    -- Get all post IDs and comment IDs in order
    SELECT ARRAY_AGG(id ORDER BY created_at) INTO post_ids FROM posts;
    SELECT ARRAY_AGG(id ORDER BY created_at) INTO comment_ids FROM comments;
    
    -- Reactions on posts
    INSERT INTO reactions (content_id, user_id) VALUES
    -- Post 1 (PostgreSQL book)
    (post_ids[1], 2), (post_ids[1], 3), (post_ids[1], 4), (post_ids[1], 5),
    -- Post 2 (sunset)
    (post_ids[2], 1), (post_ids[2], 3), (post_ids[2], 4), (post_ids[2], 5), (post_ids[2], 6),
    -- Post 3 (weekend)
    (post_ids[3], 1), (post_ids[3], 2), (post_ids[3], 4),
    -- Post 4 (coding project)
    (post_ids[4], 1), (post_ids[4], 2), (post_ids[4], 5), (post_ids[4], 8),
    -- Post 5 (coffee)
    (post_ids[5], 1), (post_ids[5], 2), (post_ids[5], 6), (post_ids[5], 10),
    -- Post 16 (first production app)
    (post_ids[16], 2), (post_ids[16], 3), (post_ids[16], 4), (post_ids[16], 5), (post_ids[16], 6), (post_ids[16], 7),
    -- Post 17 (Learning React)
    (post_ids[17], 1), (post_ids[17], 4), (post_ids[17], 9),
    -- Post 19 (Database optimization)
    (post_ids[19], 1), (post_ids[19], 2), (post_ids[19], 10);

    -- Reactions on comments
    INSERT INTO reactions (content_id, user_id) VALUES
    -- Comment reactions (various comments getting likes)
    (comment_ids[1], 1), (comment_ids[1], 4), -- "What book was it?"
    (comment_ids[2], 1), (comment_ids[2], 2), -- "Triggers can be tricky"
    (comment_ids[4], 2), (comment_ids[4], 5), -- "Which beach?"
    (comment_ids[7], 3), (comment_ids[7], 7), -- "Me! Planning to catch up"
    (comment_ids[10], 4), (comment_ids[10], 9), -- "What tech stack?"
    (comment_ids[15], 2), (comment_ids[15], 6), -- "How about Clean Code?"
    (comment_ids[19], 1); -- "Congratulations!"
END $$;

------------------------------------------
-- IMAGES
------------------------------------------
-- DO $$
-- DECLARE
--     post_ids BIGINT[];
--     comment_ids BIGINT[];
--     event_ids BIGINT[];
-- BEGIN
--     -- Get all IDs in order
--     SELECT ARRAY_AGG(id ORDER BY created_at) INTO post_ids FROM posts;
--     SELECT ARRAY_AGG(id ORDER BY created_at) INTO comment_ids FROM comments;
--     SELECT ARRAY_AGG(id ORDER BY created_at) INTO event_ids FROM events;
    
--     -- Images for posts
--     -- Post 2 (sunset) - multiple images
--     INSERT INTO images (id, parent_id, sort_order) VALUES
--     (1001, post_ids[2], 1),
--     (1002, post_ids[2], 2),
--     (1003, post_ids[2], 3);

--     -- Post 4 (coding project) - screenshot
--     INSERT INTO images (id, parent_id, sort_order) VALUES
--     (1004, post_ids[4], 1),
--     (1005, post_ids[4], 2);

--     -- Post 5 (coffee and code)
--     INSERT INTO images (id, parent_id, sort_order) VALUES
--     (1006, post_ids[5], 1);

--     -- Post 16 (first production app) - app screenshots
--     INSERT INTO images (id, parent_id, sort_order) VALUES
--     (1007, post_ids[16], 1),
--     (1008, post_ids[16], 2),
--     (1009, post_ids[16], 3),
--     (1010, post_ids[16], 4);

--     -- Group post images
--     INSERT INTO images (id, parent_id, sort_order) VALUES
--     (1011, post_ids[8], 1), -- Book club post
--     (1012, post_ids[12], 1); -- Hiking trip post

--     -- Event images
--     INSERT INTO images (id, parent_id, sort_order) VALUES
--     (1013, event_ids[4], 1), -- Hiking event
--     (1014, event_ids[4], 2),
--     (1015, event_ids[6], 1); -- Company picnic

--     -- Comment with image
--     INSERT INTO images (id, parent_id, sort_order) VALUES
--     (1016, comment_ids[4], 1); -- Image on "Which beach?" comment
-- END $$;

COMMIT;

-- Verification queries (optional - uncomment to see results)
-- SELECT 'Posts created:', COUNT(*) FROM posts;
-- SELECT 'Comments created:', COUNT(*) FROM comments;
-- SELECT 'Events created:', COUNT(*) FROM events;
-- SELECT 'Event responses:', COUNT(*) FROM event_responses;
-- SELECT 'Reactions created:', COUNT(*) FROM reactions;
-- SELECT 'Images created:', COUNT(*) FROM images;
-- SELECT 'Master index entries:', COUNT(*) FROM master_index;