// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: users.proto

package users

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	common "social-network/shared/gen-go/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_RegisterUser_FullMethodName                     = "/users.UserService/RegisterUser"
	UserService_LoginUser_FullMethodName                        = "/users.UserService/LoginUser"
	UserService_UpdateUserPassword_FullMethodName               = "/users.UserService/UpdateUserPassword"
	UserService_UpdateUserEmail_FullMethodName                  = "/users.UserService/UpdateUserEmail"
	UserService_GetFollowersPaginated_FullMethodName            = "/users.UserService/GetFollowersPaginated"
	UserService_GetFollowingPaginated_FullMethodName            = "/users.UserService/GetFollowingPaginated"
	UserService_FollowUser_FullMethodName                       = "/users.UserService/FollowUser"
	UserService_UnFollowUser_FullMethodName                     = "/users.UserService/UnFollowUser"
	UserService_HandleFollowRequest_FullMethodName              = "/users.UserService/HandleFollowRequest"
	UserService_GetFollowingIds_FullMethodName                  = "/users.UserService/GetFollowingIds"
	UserService_GetFollowSuggestions_FullMethodName             = "/users.UserService/GetFollowSuggestions"
	UserService_IsFollowing_FullMethodName                      = "/users.UserService/IsFollowing"
	UserService_AreFollowingEachOther_FullMethodName            = "/users.UserService/AreFollowingEachOther"
	UserService_GetAllGroupsPaginated_FullMethodName            = "/users.UserService/GetAllGroupsPaginated"
	UserService_GetUserGroupsPaginated_FullMethodName           = "/users.UserService/GetUserGroupsPaginated"
	UserService_GetGroupInfo_FullMethodName                     = "/users.UserService/GetGroupInfo"
	UserService_GetGroupBasicInfo_FullMethodName                = "/users.UserService/GetGroupBasicInfo"
	UserService_GetGroupMembers_FullMethodName                  = "/users.UserService/GetGroupMembers"
	UserService_GetAllGroupMemberIds_FullMethodName             = "/users.UserService/GetAllGroupMemberIds"
	UserService_GetPendingGroupJoinRequests_FullMethodName      = "/users.UserService/GetPendingGroupJoinRequests"
	UserService_GetPendingGroupJoinRequestsCount_FullMethodName = "/users.UserService/GetPendingGroupJoinRequestsCount"
	UserService_GetFollowersNotInvitedToGroup_FullMethodName    = "/users.UserService/GetFollowersNotInvitedToGroup"
	UserService_SearchGroups_FullMethodName                     = "/users.UserService/SearchGroups"
	UserService_InviteToGroup_FullMethodName                    = "/users.UserService/InviteToGroup"
	UserService_IsGroupMember_FullMethodName                    = "/users.UserService/IsGroupMember"
	UserService_RequestJoinGroup_FullMethodName                 = "/users.UserService/RequestJoinGroup"
	UserService_CancelJoinGroupRequest_FullMethodName           = "/users.UserService/CancelJoinGroupRequest"
	UserService_RespondToGroupInvite_FullMethodName             = "/users.UserService/RespondToGroupInvite"
	UserService_HandleGroupJoinRequest_FullMethodName           = "/users.UserService/HandleGroupJoinRequest"
	UserService_LeaveGroup_FullMethodName                       = "/users.UserService/LeaveGroup"
	UserService_RemoveFromGroup_FullMethodName                  = "/users.UserService/RemoveFromGroup"
	UserService_CreateGroup_FullMethodName                      = "/users.UserService/CreateGroup"
	UserService_UpdateGroup_FullMethodName                      = "/users.UserService/UpdateGroup"
	UserService_GetBasicUserInfo_FullMethodName                 = "/users.UserService/GetBasicUserInfo"
	UserService_GetBatchBasicUserInfo_FullMethodName            = "/users.UserService/GetBatchBasicUserInfo"
	UserService_GetUserProfile_FullMethodName                   = "/users.UserService/GetUserProfile"
	UserService_SearchUsers_FullMethodName                      = "/users.UserService/SearchUsers"
	UserService_UpdateUserProfile_FullMethodName                = "/users.UserService/UpdateUserProfile"
	UserService_UpdateProfilePrivacy_FullMethodName             = "/users.UserService/UpdateProfilePrivacy"
	UserService_RemoveImages_FullMethodName                     = "/users.UserService/RemoveImages"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UserService covers auth, follow, group, and profile operations.
type UserServiceClient interface {
	// Registers a new account and returns userId and Username.
	// Returns already exists if email is already in the database.
	RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
	// Authenticates by username/email identifier and hashed password.
	// Avoid using username as it's not unique, only email is.
	// Returns basic user info (id, username, avatar url).
	// Calls users and media service for user info and avatar url.
	// Returns invalid argument if identifier and password don't return any rows.
	LoginUser(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*common.User, error)
	// Updates a user's password after verifying the current password.
	// Returns permission denied if given old password doesn't match the one in the db.
	UpdateUserPassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Updates the account email address.
	UpdateUserEmail(ctx context.Context, in *UpdateEmailRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Returns followers of a user with pagination, ordered by most recent follow first.
	// Calls users and media service for user info and avatar url.
	GetFollowersPaginated(ctx context.Context, in *Pagination, opts ...grpc.CallOption) (*common.ListUsers, error)
	// Returns accounts the user is following with pagination, ordered my most recent follow first.
	// Calls users and media service for user info and avatar url.
	GetFollowingPaginated(ctx context.Context, in *Pagination, opts ...grpc.CallOption) (*common.ListUsers, error)
	// Follows a target user if profile is public, or creates a pending request for private profiles.
	// Returns invalid argument if user tries to follow self, not found if target user doesn't exist or isn't marked active.
	// Returns two mutually exclusive booleans, IsPending and ViewerIsFollowing, to show whether the follow was pending or completed.
	FollowUser(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*FollowUserResponse, error)
	// Unfollows a target user or cancels a pending follow request.
	UnFollowUser(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Accepts or rejects a pending follow request.
	HandleFollowRequest(ctx context.Context, in *HandleFollowRequestRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Returns ids that the user is following.
	GetFollowingIds(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc.CallOption) (*common.UserIds, error)
	// Returns a ranked list of user follow suggestions for the given user, based on
	// second-degree follows (people followed by users you follow) and shared group
	// memberships. Suggestions are weighted by interaction type, exclude the user
	// themself and users already followed, and return the top results with slight
	// randomization to avoid deterministic ordering.
	GetFollowSuggestions(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc.CallOption) (*common.ListUsers, error)
	// Returns whether follower_id currently follows target_user_id.
	IsFollowing(ctx context.Context, in *IsFollowingRequest, opts ...grpc.CallOption) (*wrapperspb.BoolValue, error)
	// Returns two booleans indicating whether follower_id follows target_user_id and vice versa.
	AreFollowingEachOther(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*AreFollowingEachOtherResponse, error)
	// Returns all available groups paginated, ordered by most members first.
	// Includes owner id, members count, and requester's group role if any (member, owner, pending)
	// Calls media service for image urls
	GetAllGroupsPaginated(ctx context.Context, in *Pagination, opts ...grpc.CallOption) (*GroupArr, error)
	// Returns groups the user belongs to with pagination, ordered by latest joined first
	// Includes owner id, members count, and requester's group role if any (member, owner, pending)
	// Calls media service for image urls
	GetUserGroupsPaginated(ctx context.Context, in *Pagination, opts ...grpc.CallOption) (*GroupArr, error)
	// Returns details for a single group.
	// Includes owner id, members count, and requester's group role if any (member, owner, pending)
	// Calls media service for image urls.
	GetGroupInfo(ctx context.Context, in *GeneralGroupRequest, opts ...grpc.CallOption) (*Group, error)
	// Returns only the basic group info (owner id, title, description, image id)
	GetGroupBasicInfo(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Group, error)
	// Returns members of a group with pagination, ordered by latest joined first
	// Returns permission denied if requester is not a group member.
	// Calls users and media service for user info and avatar urls.
	GetGroupMembers(ctx context.Context, in *GroupMembersRequest, opts ...grpc.CallOption) (*GroupUserArr, error)
	// Returns all member ids of a given group
	GetAllGroupMemberIds(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ids, error)
	// Returns all pending group requests with user information for group owner.
	// Includes pagination, results are sorted by ascending join request date
	// Returns permission denied if requester is not the group owner.
	// Calls users and media service for user info and avatar urls.
	GetPendingGroupJoinRequests(ctx context.Context, in *GroupMembersRequest, opts ...grpc.CallOption) (*common.ListUsers, error)
	// Returns the total count of all pending group requests for group owner.
	// Returns permission denied if requester is not the group owner.
	GetPendingGroupJoinRequestsCount(ctx context.Context, in *GeneralGroupRequest, opts ...grpc.CallOption) (*CountResp, error)
	// Returns paginated user's followers who have not yet been invited to join the group.
	// Results are sorted by descending follow date.
	// Returns permission denied if requester is not a group member.
	// Calls users and media service for user info and avatar urls.
	GetFollowersNotInvitedToGroup(ctx context.Context, in *GroupMembersRequest, opts ...grpc.CallOption) (*common.ListUsers, error)
	// Searches active groups by title and description using substring and fuzzy
	// matching, ranks results by relevance, and annotates whether the requesting
	// user is a member or owner. Results are ordered by score and popularity and
	// support pagination.
	// Score is computed from the search query’s similarity to a group’s title and
	// description: for queries of length 3 or more, fuzzy similarity is used with
	// higher weight on title matches; for shorter queries, simple substring matches
	// are scored instead. Popularity is measured by the group’s members_count, with
	// groups the user already belongs to ranked ahead of others.
	SearchGroups(ctx context.Context, in *GroupSearchRequest, opts ...grpc.CallOption) (*GroupArr, error)
	// Invites a list of users to join a group.
	// Returns permission denied if inviter is not a group member.
	// If invite already exists it's update to "pending".
	InviteToGroup(ctx context.Context, in *InviteToGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Checks if the requester is a member of the given group.
	// The onwer is also treated as a member.
	IsGroupMember(ctx context.Context, in *GeneralGroupRequest, opts ...grpc.CallOption) (*wrapperspb.BoolValue, error)
	// Creates a join request for the group.
	// If the request already exists it updates to "pending".
	RequestJoinGroup(ctx context.Context, in *GroupJoinRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Cancels a request to join the group.
	CancelJoinGroupRequest(ctx context.Context, in *GroupJoinRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Accepts or declines a received group invite.
	RespondToGroupInvite(ctx context.Context, in *HandleGroupInviteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Approves or rejects a user's join request.
	// Returns permission declined if user handling the request is not owner of the group.
	HandleGroupJoinRequest(ctx context.Context, in *HandleJoinRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Removes user as member of the specified group.
	// Returns permission denied if user wasn't a member of the group.
	LeaveGroup(ctx context.Context, in *GeneralGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Removes a group member from the group.
	// Returns permission denied if requester is not the owner of the group.
	// Owner cannot be removed.
	RemoveFromGroup(ctx context.Context, in *RemoveFromGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Creates a new group with requester as owner and returns its id.
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*wrapperspb.Int64Value, error)
	// Updates group info (title, description, image).
	// Returns permission denied if requester is not group owner.
	// All fields must be included even if they remain unchanged or they will be deleted.
	UpdateGroup(ctx context.Context, in *UpdateGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Retrieves basic public info for a user (id, username, avatar id).
	// Does not call media service for avatar url
	// Returns no rows for id not found.
	GetBasicUserInfo(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc.CallOption) (*common.User, error)
	// Retrieves basic info for multiple users (id, username, avatar id).
	// Does not call media service for avatar url
	// Returns any users found on db, or no rows if no ids are found. Missing users are silently skipped.
	GetBatchBasicUserInfo(ctx context.Context, in *common.UserIds, opts ...grpc.CallOption) (*common.ListUsers, error)
	// Returns the full profile
	// Includes following, followers and group counts.
	// Also includes viewer specific info: whether it's own profile and whether the viewer is following or has pending follow request.
	// Calls media service for avatar url.
	GetUserProfile(ctx context.Context, in *GetUserProfileRequest, opts ...grpc.CallOption) (*UserProfileResponse, error)
	// Searches active users by username, first name, or last name using prefix
	// matching for short queries and fuzzy similarity for longer queries. Results
	// are ordered by relevance and limited to at most the requested limit,
	// with username-based alphabetical ordering used to ensure consistent ordering
	// when relevance scores are equal.
	SearchUsers(ctx context.Context, in *UserSearchRequest, opts ...grpc.CallOption) (*common.ListUsers, error)
	// Updates profile fields for the given user and returns it.
	// All fields must be included even if unchanged or they will be deleted.
	// Calls media service for avatar url.
	// Sets/updates cached basic user info to avoid outdated data.
	UpdateUserProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UserProfileResponse, error)
	// Toggles public/private profile visibility (public/private).
	UpdateProfilePrivacy(ctx context.Context, in *UpdateProfilePrivacyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Resets failed or missing avatar ids to 0
	RemoveImages(ctx context.Context, in *FailedImageIds, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterUserResponse)
	err := c.cc.Invoke(ctx, UserService_RegisterUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) LoginUser(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*common.User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.User)
	err := c.cc.Invoke(ctx, UserService_LoginUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUserPassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserService_UpdateUserPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUserEmail(ctx context.Context, in *UpdateEmailRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserService_UpdateUserEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetFollowersPaginated(ctx context.Context, in *Pagination, opts ...grpc.CallOption) (*common.ListUsers, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.ListUsers)
	err := c.cc.Invoke(ctx, UserService_GetFollowersPaginated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetFollowingPaginated(ctx context.Context, in *Pagination, opts ...grpc.CallOption) (*common.ListUsers, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.ListUsers)
	err := c.cc.Invoke(ctx, UserService_GetFollowingPaginated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) FollowUser(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*FollowUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowUserResponse)
	err := c.cc.Invoke(ctx, UserService_FollowUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UnFollowUser(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserService_UnFollowUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) HandleFollowRequest(ctx context.Context, in *HandleFollowRequestRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserService_HandleFollowRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetFollowingIds(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc.CallOption) (*common.UserIds, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.UserIds)
	err := c.cc.Invoke(ctx, UserService_GetFollowingIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetFollowSuggestions(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc.CallOption) (*common.ListUsers, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.ListUsers)
	err := c.cc.Invoke(ctx, UserService_GetFollowSuggestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) IsFollowing(ctx context.Context, in *IsFollowingRequest, opts ...grpc.CallOption) (*wrapperspb.BoolValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(wrapperspb.BoolValue)
	err := c.cc.Invoke(ctx, UserService_IsFollowing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AreFollowingEachOther(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*AreFollowingEachOtherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AreFollowingEachOtherResponse)
	err := c.cc.Invoke(ctx, UserService_AreFollowingEachOther_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetAllGroupsPaginated(ctx context.Context, in *Pagination, opts ...grpc.CallOption) (*GroupArr, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupArr)
	err := c.cc.Invoke(ctx, UserService_GetAllGroupsPaginated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserGroupsPaginated(ctx context.Context, in *Pagination, opts ...grpc.CallOption) (*GroupArr, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupArr)
	err := c.cc.Invoke(ctx, UserService_GetUserGroupsPaginated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetGroupInfo(ctx context.Context, in *GeneralGroupRequest, opts ...grpc.CallOption) (*Group, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Group)
	err := c.cc.Invoke(ctx, UserService_GetGroupInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetGroupBasicInfo(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Group, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Group)
	err := c.cc.Invoke(ctx, UserService_GetGroupBasicInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetGroupMembers(ctx context.Context, in *GroupMembersRequest, opts ...grpc.CallOption) (*GroupUserArr, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupUserArr)
	err := c.cc.Invoke(ctx, UserService_GetGroupMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetAllGroupMemberIds(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Ids, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ids)
	err := c.cc.Invoke(ctx, UserService_GetAllGroupMemberIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetPendingGroupJoinRequests(ctx context.Context, in *GroupMembersRequest, opts ...grpc.CallOption) (*common.ListUsers, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.ListUsers)
	err := c.cc.Invoke(ctx, UserService_GetPendingGroupJoinRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetPendingGroupJoinRequestsCount(ctx context.Context, in *GeneralGroupRequest, opts ...grpc.CallOption) (*CountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountResp)
	err := c.cc.Invoke(ctx, UserService_GetPendingGroupJoinRequestsCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetFollowersNotInvitedToGroup(ctx context.Context, in *GroupMembersRequest, opts ...grpc.CallOption) (*common.ListUsers, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.ListUsers)
	err := c.cc.Invoke(ctx, UserService_GetFollowersNotInvitedToGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SearchGroups(ctx context.Context, in *GroupSearchRequest, opts ...grpc.CallOption) (*GroupArr, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupArr)
	err := c.cc.Invoke(ctx, UserService_SearchGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) InviteToGroup(ctx context.Context, in *InviteToGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserService_InviteToGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) IsGroupMember(ctx context.Context, in *GeneralGroupRequest, opts ...grpc.CallOption) (*wrapperspb.BoolValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(wrapperspb.BoolValue)
	err := c.cc.Invoke(ctx, UserService_IsGroupMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RequestJoinGroup(ctx context.Context, in *GroupJoinRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserService_RequestJoinGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CancelJoinGroupRequest(ctx context.Context, in *GroupJoinRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserService_CancelJoinGroupRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RespondToGroupInvite(ctx context.Context, in *HandleGroupInviteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserService_RespondToGroupInvite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) HandleGroupJoinRequest(ctx context.Context, in *HandleJoinRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserService_HandleGroupJoinRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) LeaveGroup(ctx context.Context, in *GeneralGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserService_LeaveGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RemoveFromGroup(ctx context.Context, in *RemoveFromGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserService_RemoveFromGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*wrapperspb.Int64Value, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(wrapperspb.Int64Value)
	err := c.cc.Invoke(ctx, UserService_CreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateGroup(ctx context.Context, in *UpdateGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserService_UpdateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetBasicUserInfo(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc.CallOption) (*common.User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.User)
	err := c.cc.Invoke(ctx, UserService_GetBasicUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetBatchBasicUserInfo(ctx context.Context, in *common.UserIds, opts ...grpc.CallOption) (*common.ListUsers, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.ListUsers)
	err := c.cc.Invoke(ctx, UserService_GetBatchBasicUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserProfile(ctx context.Context, in *GetUserProfileRequest, opts ...grpc.CallOption) (*UserProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserProfileResponse)
	err := c.cc.Invoke(ctx, UserService_GetUserProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SearchUsers(ctx context.Context, in *UserSearchRequest, opts ...grpc.CallOption) (*common.ListUsers, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.ListUsers)
	err := c.cc.Invoke(ctx, UserService_SearchUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUserProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UserProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserProfileResponse)
	err := c.cc.Invoke(ctx, UserService_UpdateUserProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateProfilePrivacy(ctx context.Context, in *UpdateProfilePrivacyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserService_UpdateProfilePrivacy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RemoveImages(ctx context.Context, in *FailedImageIds, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserService_RemoveImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
//
// UserService covers auth, follow, group, and profile operations.
type UserServiceServer interface {
	// Registers a new account and returns userId and Username.
	// Returns already exists if email is already in the database.
	RegisterUser(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error)
	// Authenticates by username/email identifier and hashed password.
	// Avoid using username as it's not unique, only email is.
	// Returns basic user info (id, username, avatar url).
	// Calls users and media service for user info and avatar url.
	// Returns invalid argument if identifier and password don't return any rows.
	LoginUser(context.Context, *LoginRequest) (*common.User, error)
	// Updates a user's password after verifying the current password.
	// Returns permission denied if given old password doesn't match the one in the db.
	UpdateUserPassword(context.Context, *UpdatePasswordRequest) (*emptypb.Empty, error)
	// Updates the account email address.
	UpdateUserEmail(context.Context, *UpdateEmailRequest) (*emptypb.Empty, error)
	// Returns followers of a user with pagination, ordered by most recent follow first.
	// Calls users and media service for user info and avatar url.
	GetFollowersPaginated(context.Context, *Pagination) (*common.ListUsers, error)
	// Returns accounts the user is following with pagination, ordered my most recent follow first.
	// Calls users and media service for user info and avatar url.
	GetFollowingPaginated(context.Context, *Pagination) (*common.ListUsers, error)
	// Follows a target user if profile is public, or creates a pending request for private profiles.
	// Returns invalid argument if user tries to follow self, not found if target user doesn't exist or isn't marked active.
	// Returns two mutually exclusive booleans, IsPending and ViewerIsFollowing, to show whether the follow was pending or completed.
	FollowUser(context.Context, *FollowUserRequest) (*FollowUserResponse, error)
	// Unfollows a target user or cancels a pending follow request.
	UnFollowUser(context.Context, *FollowUserRequest) (*emptypb.Empty, error)
	// Accepts or rejects a pending follow request.
	HandleFollowRequest(context.Context, *HandleFollowRequestRequest) (*emptypb.Empty, error)
	// Returns ids that the user is following.
	GetFollowingIds(context.Context, *wrapperspb.Int64Value) (*common.UserIds, error)
	// Returns a ranked list of user follow suggestions for the given user, based on
	// second-degree follows (people followed by users you follow) and shared group
	// memberships. Suggestions are weighted by interaction type, exclude the user
	// themself and users already followed, and return the top results with slight
	// randomization to avoid deterministic ordering.
	GetFollowSuggestions(context.Context, *wrapperspb.Int64Value) (*common.ListUsers, error)
	// Returns whether follower_id currently follows target_user_id.
	IsFollowing(context.Context, *IsFollowingRequest) (*wrapperspb.BoolValue, error)
	// Returns two booleans indicating whether follower_id follows target_user_id and vice versa.
	AreFollowingEachOther(context.Context, *FollowUserRequest) (*AreFollowingEachOtherResponse, error)
	// Returns all available groups paginated, ordered by most members first.
	// Includes owner id, members count, and requester's group role if any (member, owner, pending)
	// Calls media service for image urls
	GetAllGroupsPaginated(context.Context, *Pagination) (*GroupArr, error)
	// Returns groups the user belongs to with pagination, ordered by latest joined first
	// Includes owner id, members count, and requester's group role if any (member, owner, pending)
	// Calls media service for image urls
	GetUserGroupsPaginated(context.Context, *Pagination) (*GroupArr, error)
	// Returns details for a single group.
	// Includes owner id, members count, and requester's group role if any (member, owner, pending)
	// Calls media service for image urls.
	GetGroupInfo(context.Context, *GeneralGroupRequest) (*Group, error)
	// Returns only the basic group info (owner id, title, description, image id)
	GetGroupBasicInfo(context.Context, *IdReq) (*Group, error)
	// Returns members of a group with pagination, ordered by latest joined first
	// Returns permission denied if requester is not a group member.
	// Calls users and media service for user info and avatar urls.
	GetGroupMembers(context.Context, *GroupMembersRequest) (*GroupUserArr, error)
	// Returns all member ids of a given group
	GetAllGroupMemberIds(context.Context, *IdReq) (*Ids, error)
	// Returns all pending group requests with user information for group owner.
	// Includes pagination, results are sorted by ascending join request date
	// Returns permission denied if requester is not the group owner.
	// Calls users and media service for user info and avatar urls.
	GetPendingGroupJoinRequests(context.Context, *GroupMembersRequest) (*common.ListUsers, error)
	// Returns the total count of all pending group requests for group owner.
	// Returns permission denied if requester is not the group owner.
	GetPendingGroupJoinRequestsCount(context.Context, *GeneralGroupRequest) (*CountResp, error)
	// Returns paginated user's followers who have not yet been invited to join the group.
	// Results are sorted by descending follow date.
	// Returns permission denied if requester is not a group member.
	// Calls users and media service for user info and avatar urls.
	GetFollowersNotInvitedToGroup(context.Context, *GroupMembersRequest) (*common.ListUsers, error)
	// Searches active groups by title and description using substring and fuzzy
	// matching, ranks results by relevance, and annotates whether the requesting
	// user is a member or owner. Results are ordered by score and popularity and
	// support pagination.
	// Score is computed from the search query’s similarity to a group’s title and
	// description: for queries of length 3 or more, fuzzy similarity is used with
	// higher weight on title matches; for shorter queries, simple substring matches
	// are scored instead. Popularity is measured by the group’s members_count, with
	// groups the user already belongs to ranked ahead of others.
	SearchGroups(context.Context, *GroupSearchRequest) (*GroupArr, error)
	// Invites a list of users to join a group.
	// Returns permission denied if inviter is not a group member.
	// If invite already exists it's update to "pending".
	InviteToGroup(context.Context, *InviteToGroupRequest) (*emptypb.Empty, error)
	// Checks if the requester is a member of the given group.
	// The onwer is also treated as a member.
	IsGroupMember(context.Context, *GeneralGroupRequest) (*wrapperspb.BoolValue, error)
	// Creates a join request for the group.
	// If the request already exists it updates to "pending".
	RequestJoinGroup(context.Context, *GroupJoinRequest) (*emptypb.Empty, error)
	// Cancels a request to join the group.
	CancelJoinGroupRequest(context.Context, *GroupJoinRequest) (*emptypb.Empty, error)
	// Accepts or declines a received group invite.
	RespondToGroupInvite(context.Context, *HandleGroupInviteRequest) (*emptypb.Empty, error)
	// Approves or rejects a user's join request.
	// Returns permission declined if user handling the request is not owner of the group.
	HandleGroupJoinRequest(context.Context, *HandleJoinRequest) (*emptypb.Empty, error)
	// Removes user as member of the specified group.
	// Returns permission denied if user wasn't a member of the group.
	LeaveGroup(context.Context, *GeneralGroupRequest) (*emptypb.Empty, error)
	// Removes a group member from the group.
	// Returns permission denied if requester is not the owner of the group.
	// Owner cannot be removed.
	RemoveFromGroup(context.Context, *RemoveFromGroupRequest) (*emptypb.Empty, error)
	// Creates a new group with requester as owner and returns its id.
	CreateGroup(context.Context, *CreateGroupRequest) (*wrapperspb.Int64Value, error)
	// Updates group info (title, description, image).
	// Returns permission denied if requester is not group owner.
	// All fields must be included even if they remain unchanged or they will be deleted.
	UpdateGroup(context.Context, *UpdateGroupRequest) (*emptypb.Empty, error)
	// Retrieves basic public info for a user (id, username, avatar id).
	// Does not call media service for avatar url
	// Returns no rows for id not found.
	GetBasicUserInfo(context.Context, *wrapperspb.Int64Value) (*common.User, error)
	// Retrieves basic info for multiple users (id, username, avatar id).
	// Does not call media service for avatar url
	// Returns any users found on db, or no rows if no ids are found. Missing users are silently skipped.
	GetBatchBasicUserInfo(context.Context, *common.UserIds) (*common.ListUsers, error)
	// Returns the full profile
	// Includes following, followers and group counts.
	// Also includes viewer specific info: whether it's own profile and whether the viewer is following or has pending follow request.
	// Calls media service for avatar url.
	GetUserProfile(context.Context, *GetUserProfileRequest) (*UserProfileResponse, error)
	// Searches active users by username, first name, or last name using prefix
	// matching for short queries and fuzzy similarity for longer queries. Results
	// are ordered by relevance and limited to at most the requested limit,
	// with username-based alphabetical ordering used to ensure consistent ordering
	// when relevance scores are equal.
	SearchUsers(context.Context, *UserSearchRequest) (*common.ListUsers, error)
	// Updates profile fields for the given user and returns it.
	// All fields must be included even if unchanged or they will be deleted.
	// Calls media service for avatar url.
	// Sets/updates cached basic user info to avoid outdated data.
	UpdateUserProfile(context.Context, *UpdateProfileRequest) (*UserProfileResponse, error)
	// Toggles public/private profile visibility (public/private).
	UpdateProfilePrivacy(context.Context, *UpdateProfilePrivacyRequest) (*emptypb.Empty, error)
	// Resets failed or missing avatar ids to 0
	RemoveImages(context.Context, *FailedImageIds) (*emptypb.Empty, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) RegisterUser(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterUser not implemented")
}
func (UnimplementedUserServiceServer) LoginUser(context.Context, *LoginRequest) (*common.User, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedUserServiceServer) UpdateUserPassword(context.Context, *UpdatePasswordRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserPassword not implemented")
}
func (UnimplementedUserServiceServer) UpdateUserEmail(context.Context, *UpdateEmailRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserEmail not implemented")
}
func (UnimplementedUserServiceServer) GetFollowersPaginated(context.Context, *Pagination) (*common.ListUsers, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFollowersPaginated not implemented")
}
func (UnimplementedUserServiceServer) GetFollowingPaginated(context.Context, *Pagination) (*common.ListUsers, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFollowingPaginated not implemented")
}
func (UnimplementedUserServiceServer) FollowUser(context.Context, *FollowUserRequest) (*FollowUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FollowUser not implemented")
}
func (UnimplementedUserServiceServer) UnFollowUser(context.Context, *FollowUserRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnFollowUser not implemented")
}
func (UnimplementedUserServiceServer) HandleFollowRequest(context.Context, *HandleFollowRequestRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleFollowRequest not implemented")
}
func (UnimplementedUserServiceServer) GetFollowingIds(context.Context, *wrapperspb.Int64Value) (*common.UserIds, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFollowingIds not implemented")
}
func (UnimplementedUserServiceServer) GetFollowSuggestions(context.Context, *wrapperspb.Int64Value) (*common.ListUsers, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFollowSuggestions not implemented")
}
func (UnimplementedUserServiceServer) IsFollowing(context.Context, *IsFollowingRequest) (*wrapperspb.BoolValue, error) {
	return nil, status.Error(codes.Unimplemented, "method IsFollowing not implemented")
}
func (UnimplementedUserServiceServer) AreFollowingEachOther(context.Context, *FollowUserRequest) (*AreFollowingEachOtherResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AreFollowingEachOther not implemented")
}
func (UnimplementedUserServiceServer) GetAllGroupsPaginated(context.Context, *Pagination) (*GroupArr, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllGroupsPaginated not implemented")
}
func (UnimplementedUserServiceServer) GetUserGroupsPaginated(context.Context, *Pagination) (*GroupArr, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserGroupsPaginated not implemented")
}
func (UnimplementedUserServiceServer) GetGroupInfo(context.Context, *GeneralGroupRequest) (*Group, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupInfo not implemented")
}
func (UnimplementedUserServiceServer) GetGroupBasicInfo(context.Context, *IdReq) (*Group, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupBasicInfo not implemented")
}
func (UnimplementedUserServiceServer) GetGroupMembers(context.Context, *GroupMembersRequest) (*GroupUserArr, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupMembers not implemented")
}
func (UnimplementedUserServiceServer) GetAllGroupMemberIds(context.Context, *IdReq) (*Ids, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllGroupMemberIds not implemented")
}
func (UnimplementedUserServiceServer) GetPendingGroupJoinRequests(context.Context, *GroupMembersRequest) (*common.ListUsers, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPendingGroupJoinRequests not implemented")
}
func (UnimplementedUserServiceServer) GetPendingGroupJoinRequestsCount(context.Context, *GeneralGroupRequest) (*CountResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPendingGroupJoinRequestsCount not implemented")
}
func (UnimplementedUserServiceServer) GetFollowersNotInvitedToGroup(context.Context, *GroupMembersRequest) (*common.ListUsers, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFollowersNotInvitedToGroup not implemented")
}
func (UnimplementedUserServiceServer) SearchGroups(context.Context, *GroupSearchRequest) (*GroupArr, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchGroups not implemented")
}
func (UnimplementedUserServiceServer) InviteToGroup(context.Context, *InviteToGroupRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method InviteToGroup not implemented")
}
func (UnimplementedUserServiceServer) IsGroupMember(context.Context, *GeneralGroupRequest) (*wrapperspb.BoolValue, error) {
	return nil, status.Error(codes.Unimplemented, "method IsGroupMember not implemented")
}
func (UnimplementedUserServiceServer) RequestJoinGroup(context.Context, *GroupJoinRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestJoinGroup not implemented")
}
func (UnimplementedUserServiceServer) CancelJoinGroupRequest(context.Context, *GroupJoinRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelJoinGroupRequest not implemented")
}
func (UnimplementedUserServiceServer) RespondToGroupInvite(context.Context, *HandleGroupInviteRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RespondToGroupInvite not implemented")
}
func (UnimplementedUserServiceServer) HandleGroupJoinRequest(context.Context, *HandleJoinRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleGroupJoinRequest not implemented")
}
func (UnimplementedUserServiceServer) LeaveGroup(context.Context, *GeneralGroupRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaveGroup not implemented")
}
func (UnimplementedUserServiceServer) RemoveFromGroup(context.Context, *RemoveFromGroupRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFromGroup not implemented")
}
func (UnimplementedUserServiceServer) CreateGroup(context.Context, *CreateGroupRequest) (*wrapperspb.Int64Value, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedUserServiceServer) UpdateGroup(context.Context, *UpdateGroupRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGroup not implemented")
}
func (UnimplementedUserServiceServer) GetBasicUserInfo(context.Context, *wrapperspb.Int64Value) (*common.User, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBasicUserInfo not implemented")
}
func (UnimplementedUserServiceServer) GetBatchBasicUserInfo(context.Context, *common.UserIds) (*common.ListUsers, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBatchBasicUserInfo not implemented")
}
func (UnimplementedUserServiceServer) GetUserProfile(context.Context, *GetUserProfileRequest) (*UserProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserProfile not implemented")
}
func (UnimplementedUserServiceServer) SearchUsers(context.Context, *UserSearchRequest) (*common.ListUsers, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchUsers not implemented")
}
func (UnimplementedUserServiceServer) UpdateUserProfile(context.Context, *UpdateProfileRequest) (*UserProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserProfile not implemented")
}
func (UnimplementedUserServiceServer) UpdateProfilePrivacy(context.Context, *UpdateProfilePrivacyRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProfilePrivacy not implemented")
}
func (UnimplementedUserServiceServer) RemoveImages(context.Context, *FailedImageIds) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveImages not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call panics, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_RegisterUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RegisterUser(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_LoginUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).LoginUser(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUserPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUserPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateUserPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUserPassword(ctx, req.(*UpdatePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUserEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUserEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateUserEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUserEmail(ctx, req.(*UpdateEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetFollowersPaginated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pagination)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetFollowersPaginated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetFollowersPaginated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetFollowersPaginated(ctx, req.(*Pagination))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetFollowingPaginated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pagination)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetFollowingPaginated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetFollowingPaginated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetFollowingPaginated(ctx, req.(*Pagination))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_FollowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).FollowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_FollowUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).FollowUser(ctx, req.(*FollowUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UnFollowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UnFollowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UnFollowUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UnFollowUser(ctx, req.(*FollowUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_HandleFollowRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleFollowRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).HandleFollowRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_HandleFollowRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).HandleFollowRequest(ctx, req.(*HandleFollowRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetFollowingIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.Int64Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetFollowingIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetFollowingIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetFollowingIds(ctx, req.(*wrapperspb.Int64Value))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetFollowSuggestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.Int64Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetFollowSuggestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetFollowSuggestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetFollowSuggestions(ctx, req.(*wrapperspb.Int64Value))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_IsFollowing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsFollowingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).IsFollowing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_IsFollowing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).IsFollowing(ctx, req.(*IsFollowingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AreFollowingEachOther_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AreFollowingEachOther(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_AreFollowingEachOther_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AreFollowingEachOther(ctx, req.(*FollowUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetAllGroupsPaginated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pagination)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetAllGroupsPaginated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetAllGroupsPaginated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetAllGroupsPaginated(ctx, req.(*Pagination))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserGroupsPaginated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pagination)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserGroupsPaginated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserGroupsPaginated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserGroupsPaginated(ctx, req.(*Pagination))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetGroupInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneralGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetGroupInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetGroupInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetGroupInfo(ctx, req.(*GeneralGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetGroupBasicInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetGroupBasicInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetGroupBasicInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetGroupBasicInfo(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetGroupMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetGroupMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetGroupMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetGroupMembers(ctx, req.(*GroupMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetAllGroupMemberIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetAllGroupMemberIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetAllGroupMemberIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetAllGroupMemberIds(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetPendingGroupJoinRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetPendingGroupJoinRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetPendingGroupJoinRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetPendingGroupJoinRequests(ctx, req.(*GroupMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetPendingGroupJoinRequestsCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneralGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetPendingGroupJoinRequestsCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetPendingGroupJoinRequestsCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetPendingGroupJoinRequestsCount(ctx, req.(*GeneralGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetFollowersNotInvitedToGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetFollowersNotInvitedToGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetFollowersNotInvitedToGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetFollowersNotInvitedToGroup(ctx, req.(*GroupMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SearchGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SearchGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_SearchGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SearchGroups(ctx, req.(*GroupSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_InviteToGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteToGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).InviteToGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_InviteToGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).InviteToGroup(ctx, req.(*InviteToGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_IsGroupMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneralGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).IsGroupMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_IsGroupMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).IsGroupMember(ctx, req.(*GeneralGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RequestJoinGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RequestJoinGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_RequestJoinGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RequestJoinGroup(ctx, req.(*GroupJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CancelJoinGroupRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CancelJoinGroupRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CancelJoinGroupRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CancelJoinGroupRequest(ctx, req.(*GroupJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RespondToGroupInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleGroupInviteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RespondToGroupInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_RespondToGroupInvite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RespondToGroupInvite(ctx, req.(*HandleGroupInviteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_HandleGroupJoinRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).HandleGroupJoinRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_HandleGroupJoinRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).HandleGroupJoinRequest(ctx, req.(*HandleJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_LeaveGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneralGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).LeaveGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_LeaveGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).LeaveGroup(ctx, req.(*GeneralGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RemoveFromGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFromGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RemoveFromGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_RemoveFromGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RemoveFromGroup(ctx, req.(*RemoveFromGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateGroup(ctx, req.(*UpdateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetBasicUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.Int64Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetBasicUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetBasicUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetBasicUserInfo(ctx, req.(*wrapperspb.Int64Value))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetBatchBasicUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.UserIds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetBatchBasicUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetBatchBasicUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetBatchBasicUserInfo(ctx, req.(*common.UserIds))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserProfile(ctx, req.(*GetUserProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SearchUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SearchUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_SearchUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SearchUsers(ctx, req.(*UserSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateUserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUserProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateProfilePrivacy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfilePrivacyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateProfilePrivacy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateProfilePrivacy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateProfilePrivacy(ctx, req.(*UpdateProfilePrivacyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RemoveImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailedImageIds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RemoveImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_RemoveImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RemoveImages(ctx, req.(*FailedImageIds))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "users.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _UserService_RegisterUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _UserService_LoginUser_Handler,
		},
		{
			MethodName: "UpdateUserPassword",
			Handler:    _UserService_UpdateUserPassword_Handler,
		},
		{
			MethodName: "UpdateUserEmail",
			Handler:    _UserService_UpdateUserEmail_Handler,
		},
		{
			MethodName: "GetFollowersPaginated",
			Handler:    _UserService_GetFollowersPaginated_Handler,
		},
		{
			MethodName: "GetFollowingPaginated",
			Handler:    _UserService_GetFollowingPaginated_Handler,
		},
		{
			MethodName: "FollowUser",
			Handler:    _UserService_FollowUser_Handler,
		},
		{
			MethodName: "UnFollowUser",
			Handler:    _UserService_UnFollowUser_Handler,
		},
		{
			MethodName: "HandleFollowRequest",
			Handler:    _UserService_HandleFollowRequest_Handler,
		},
		{
			MethodName: "GetFollowingIds",
			Handler:    _UserService_GetFollowingIds_Handler,
		},
		{
			MethodName: "GetFollowSuggestions",
			Handler:    _UserService_GetFollowSuggestions_Handler,
		},
		{
			MethodName: "IsFollowing",
			Handler:    _UserService_IsFollowing_Handler,
		},
		{
			MethodName: "AreFollowingEachOther",
			Handler:    _UserService_AreFollowingEachOther_Handler,
		},
		{
			MethodName: "GetAllGroupsPaginated",
			Handler:    _UserService_GetAllGroupsPaginated_Handler,
		},
		{
			MethodName: "GetUserGroupsPaginated",
			Handler:    _UserService_GetUserGroupsPaginated_Handler,
		},
		{
			MethodName: "GetGroupInfo",
			Handler:    _UserService_GetGroupInfo_Handler,
		},
		{
			MethodName: "GetGroupBasicInfo",
			Handler:    _UserService_GetGroupBasicInfo_Handler,
		},
		{
			MethodName: "GetGroupMembers",
			Handler:    _UserService_GetGroupMembers_Handler,
		},
		{
			MethodName: "GetAllGroupMemberIds",
			Handler:    _UserService_GetAllGroupMemberIds_Handler,
		},
		{
			MethodName: "GetPendingGroupJoinRequests",
			Handler:    _UserService_GetPendingGroupJoinRequests_Handler,
		},
		{
			MethodName: "GetPendingGroupJoinRequestsCount",
			Handler:    _UserService_GetPendingGroupJoinRequestsCount_Handler,
		},
		{
			MethodName: "GetFollowersNotInvitedToGroup",
			Handler:    _UserService_GetFollowersNotInvitedToGroup_Handler,
		},
		{
			MethodName: "SearchGroups",
			Handler:    _UserService_SearchGroups_Handler,
		},
		{
			MethodName: "InviteToGroup",
			Handler:    _UserService_InviteToGroup_Handler,
		},
		{
			MethodName: "IsGroupMember",
			Handler:    _UserService_IsGroupMember_Handler,
		},
		{
			MethodName: "RequestJoinGroup",
			Handler:    _UserService_RequestJoinGroup_Handler,
		},
		{
			MethodName: "CancelJoinGroupRequest",
			Handler:    _UserService_CancelJoinGroupRequest_Handler,
		},
		{
			MethodName: "RespondToGroupInvite",
			Handler:    _UserService_RespondToGroupInvite_Handler,
		},
		{
			MethodName: "HandleGroupJoinRequest",
			Handler:    _UserService_HandleGroupJoinRequest_Handler,
		},
		{
			MethodName: "LeaveGroup",
			Handler:    _UserService_LeaveGroup_Handler,
		},
		{
			MethodName: "RemoveFromGroup",
			Handler:    _UserService_RemoveFromGroup_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _UserService_CreateGroup_Handler,
		},
		{
			MethodName: "UpdateGroup",
			Handler:    _UserService_UpdateGroup_Handler,
		},
		{
			MethodName: "GetBasicUserInfo",
			Handler:    _UserService_GetBasicUserInfo_Handler,
		},
		{
			MethodName: "GetBatchBasicUserInfo",
			Handler:    _UserService_GetBatchBasicUserInfo_Handler,
		},
		{
			MethodName: "GetUserProfile",
			Handler:    _UserService_GetUserProfile_Handler,
		},
		{
			MethodName: "SearchUsers",
			Handler:    _UserService_SearchUsers_Handler,
		},
		{
			MethodName: "UpdateUserProfile",
			Handler:    _UserService_UpdateUserProfile_Handler,
		},
		{
			MethodName: "UpdateProfilePrivacy",
			Handler:    _UserService_UpdateProfilePrivacy_Handler,
		},
		{
			MethodName: "RemoveImages",
			Handler:    _UserService_RemoveImages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users.proto",
}
