// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Notification struct {
	ID             int64
	UserID         int64
	NotifType      string
	SourceService  string
	SourceEntityID pgtype.Int8
	Seen           pgtype.Bool
	NeedsAction    pgtype.Bool
	Acted          pgtype.Bool
	Payload        []byte
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
	Count          pgtype.Int4
}

type NotificationType struct {
	NotifType      string
	Category       pgtype.Text
	DefaultEnabled pgtype.Bool
}
