// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateNotificationType(ctx context.Context, arg CreateNotificationTypeParams) error
	DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error
	GetNotificationByID(ctx context.Context, id int64) (Notification, error)
	GetNotificationByTypeAndEntity(ctx context.Context, arg GetNotificationByTypeAndEntityParams) (Notification, error)
	GetNotificationType(ctx context.Context, notifType string) (NotificationType, error)
	GetUnreadNotificationByTypeAndEntity(ctx context.Context, arg GetUnreadNotificationByTypeAndEntityParams) (Notification, error)
	GetUserNotifications(ctx context.Context, arg GetUserNotificationsParams) ([]Notification, error)
	GetUserNotificationsCount(ctx context.Context, userID int64) (int64, error)
	GetUserUnreadNotificationsCount(ctx context.Context, userID int64) (int64, error)
	MarkAllAsRead(ctx context.Context, userID int64) error
	MarkNotificationAsActed(ctx context.Context, arg MarkNotificationAsActedParams) error
	MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) error
	UpdateNotificationCount(ctx context.Context, arg UpdateNotificationCountParams) error
}

var _ Querier = (*Queries)(nil)
