package application

import (
	"context"
	"social-network/services/notifications/internal/client"
	"social-network/services/notifications/internal/db/sqlc"

	"github.com/nats-io/nats.go"
)

// DBInterface represents the interface for database operations
// This matches the methods generated by sqlc in the Queries struct
type DBInterface interface {
	CreateNotification(ctx context.Context, arg sqlc.CreateNotificationParams) (sqlc.Notification, error)
	GetNotificationByID(ctx context.Context, id int64) (sqlc.Notification, error)
	GetUserNotifications(ctx context.Context, arg sqlc.GetUserNotificationsParams) ([]sqlc.Notification, error)
	GetUserNotificationsCount(ctx context.Context, userID int64) (int64, error)
	GetUserUnreadNotificationsCount(ctx context.Context, userID int64) (int64, error)
	MarkNotificationAsRead(ctx context.Context, arg sqlc.MarkNotificationAsReadParams) error
	MarkAllAsRead(ctx context.Context, userID int64) error
	DeleteNotification(ctx context.Context, arg sqlc.DeleteNotificationParams) error
	CreateNotificationType(ctx context.Context, arg sqlc.CreateNotificationTypeParams) error
	GetNotificationType(ctx context.Context, notifType string) (sqlc.NotificationType, error)
	UpdateNotificationCount(ctx context.Context, arg sqlc.UpdateNotificationCountParams) error
	GetUnreadNotificationByTypeAndEntity(ctx context.Context, arg sqlc.GetUnreadNotificationByTypeAndEntityParams) (sqlc.Notification, error)
	GetNotificationByTypeAndEntity(ctx context.Context, arg sqlc.GetNotificationByTypeAndEntityParams) (sqlc.Notification, error)
	MarkNotificationAsActed(ctx context.Context, arg sqlc.MarkNotificationAsActedParams) error
}

// Update the Application struct to use the interface
type Application struct {
	DB       DBInterface
	Clients  *client.Clients
	NatsConn *nats.Conn
}

// NewApplication creates a new notification application service
func NewApplication(db DBInterface, clients *client.Clients, natsConn *nats.Conn) *Application {
	return &Application{
		DB:       db,
		Clients:  clients,
		NatsConn: natsConn,
	}
}
