// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: chat.proto

package chat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatService_CreateGroupMessage_FullMethodName           = "/chat.ChatService/CreateGroupMessage"
	ChatService_GetPreviousGroupMessages_FullMethodName     = "/chat.ChatService/GetPreviousGroupMessages"
	ChatService_GetNextGroupMessages_FullMethodName         = "/chat.ChatService/GetNextGroupMessages"
	ChatService_GetPrivateConversationById_FullMethodName   = "/chat.ChatService/GetPrivateConversationById"
	ChatService_GetPrivateConversations_FullMethodName      = "/chat.ChatService/GetPrivateConversations"
	ChatService_GetConvsWithUnreadsCount_FullMethodName     = "/chat.ChatService/GetConvsWithUnreadsCount"
	ChatService_CreatePrivateMessage_FullMethodName         = "/chat.ChatService/CreatePrivateMessage"
	ChatService_GetPreviousPrivateMessages_FullMethodName   = "/chat.ChatService/GetPreviousPrivateMessages"
	ChatService_GetNextPrivateMessages_FullMethodName       = "/chat.ChatService/GetNextPrivateMessages"
	ChatService_UpdateLastReadPrivateMessage_FullMethodName = "/chat.ChatService/UpdateLastReadPrivateMessage"
)

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition for chat-related operations, including group and private messaging.
type ChatServiceClient interface {
	// Creates a new group message and returns the created message details.
	CreateGroupMessage(ctx context.Context, in *CreateGroupMessageRequest, opts ...grpc.CallOption) (*GroupMessage, error)
	// Retrieves previous group messages (older than the boundary message) for a group.
	GetPreviousGroupMessages(ctx context.Context, in *GetGroupMessagesRequest, opts ...grpc.CallOption) (*GetGroupMessagesResponse, error)
	// Retrieves next group messages (newer than the boundary message) for a group.
	GetNextGroupMessages(ctx context.Context, in *GetGroupMessagesRequest, opts ...grpc.CallOption) (*GetGroupMessagesResponse, error)
	// Retrieves a single conversation preview by conversation id.
	// Includes conversation ID, last update time, interlocutor,
	// last message, and unread count.
	GetPrivateConversationById(ctx context.Context, in *GetPrivateConversationByIdRequest, opts ...grpc.CallOption) (*PrivateConversationPreview, error)
	// Retrieves a paginated list of private conversations for a user.
	GetPrivateConversations(ctx context.Context, in *GetPrivateConversationsRequest, opts ...grpc.CallOption) (*GetPrivateConversationsResponse, error)
	// Returns the count of conversations that the user has unread messages.
	GetConvsWithUnreadsCount(ctx context.Context, in *GetConvsWithUnreadsCountRequest, opts ...grpc.CallOption) (*GetConvsWithUnreadsCountResponse, error)
	// Creates a new private message and returns the created message details.
	CreatePrivateMessage(ctx context.Context, in *CreatePrivateMessageRequest, opts ...grpc.CallOption) (*PrivateMessage, error)
	// Retrieves previous private messages (older than the boundary message) in a conversation.
	GetPreviousPrivateMessages(ctx context.Context, in *GetPrivateMessagesRequest, opts ...grpc.CallOption) (*GetPrivateMessagesResponse, error)
	// Retrieves next private messages (newer than the boundary message) in a conversation.
	GetNextPrivateMessages(ctx context.Context, in *GetPrivateMessagesRequest, opts ...grpc.CallOption) (*GetPrivateMessagesResponse, error)
	// Updates the last read message pointer for a user in a private conversation.
	UpdateLastReadPrivateMessage(ctx context.Context, in *UpdateLastReadPrivateMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) CreateGroupMessage(ctx context.Context, in *CreateGroupMessageRequest, opts ...grpc.CallOption) (*GroupMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupMessage)
	err := c.cc.Invoke(ctx, ChatService_CreateGroupMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetPreviousGroupMessages(ctx context.Context, in *GetGroupMessagesRequest, opts ...grpc.CallOption) (*GetGroupMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupMessagesResponse)
	err := c.cc.Invoke(ctx, ChatService_GetPreviousGroupMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetNextGroupMessages(ctx context.Context, in *GetGroupMessagesRequest, opts ...grpc.CallOption) (*GetGroupMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupMessagesResponse)
	err := c.cc.Invoke(ctx, ChatService_GetNextGroupMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetPrivateConversationById(ctx context.Context, in *GetPrivateConversationByIdRequest, opts ...grpc.CallOption) (*PrivateConversationPreview, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrivateConversationPreview)
	err := c.cc.Invoke(ctx, ChatService_GetPrivateConversationById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetPrivateConversations(ctx context.Context, in *GetPrivateConversationsRequest, opts ...grpc.CallOption) (*GetPrivateConversationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPrivateConversationsResponse)
	err := c.cc.Invoke(ctx, ChatService_GetPrivateConversations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetConvsWithUnreadsCount(ctx context.Context, in *GetConvsWithUnreadsCountRequest, opts ...grpc.CallOption) (*GetConvsWithUnreadsCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConvsWithUnreadsCountResponse)
	err := c.cc.Invoke(ctx, ChatService_GetConvsWithUnreadsCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) CreatePrivateMessage(ctx context.Context, in *CreatePrivateMessageRequest, opts ...grpc.CallOption) (*PrivateMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrivateMessage)
	err := c.cc.Invoke(ctx, ChatService_CreatePrivateMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetPreviousPrivateMessages(ctx context.Context, in *GetPrivateMessagesRequest, opts ...grpc.CallOption) (*GetPrivateMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPrivateMessagesResponse)
	err := c.cc.Invoke(ctx, ChatService_GetPreviousPrivateMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetNextPrivateMessages(ctx context.Context, in *GetPrivateMessagesRequest, opts ...grpc.CallOption) (*GetPrivateMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPrivateMessagesResponse)
	err := c.cc.Invoke(ctx, ChatService_GetNextPrivateMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) UpdateLastReadPrivateMessage(ctx context.Context, in *UpdateLastReadPrivateMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ChatService_UpdateLastReadPrivateMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServiceServer is the server API for ChatService service.
// All implementations must embed UnimplementedChatServiceServer
// for forward compatibility.
//
// Service definition for chat-related operations, including group and private messaging.
type ChatServiceServer interface {
	// Creates a new group message and returns the created message details.
	CreateGroupMessage(context.Context, *CreateGroupMessageRequest) (*GroupMessage, error)
	// Retrieves previous group messages (older than the boundary message) for a group.
	GetPreviousGroupMessages(context.Context, *GetGroupMessagesRequest) (*GetGroupMessagesResponse, error)
	// Retrieves next group messages (newer than the boundary message) for a group.
	GetNextGroupMessages(context.Context, *GetGroupMessagesRequest) (*GetGroupMessagesResponse, error)
	// Retrieves a single conversation preview by conversation id.
	// Includes conversation ID, last update time, interlocutor,
	// last message, and unread count.
	GetPrivateConversationById(context.Context, *GetPrivateConversationByIdRequest) (*PrivateConversationPreview, error)
	// Retrieves a paginated list of private conversations for a user.
	GetPrivateConversations(context.Context, *GetPrivateConversationsRequest) (*GetPrivateConversationsResponse, error)
	// Returns the count of conversations that the user has unread messages.
	GetConvsWithUnreadsCount(context.Context, *GetConvsWithUnreadsCountRequest) (*GetConvsWithUnreadsCountResponse, error)
	// Creates a new private message and returns the created message details.
	CreatePrivateMessage(context.Context, *CreatePrivateMessageRequest) (*PrivateMessage, error)
	// Retrieves previous private messages (older than the boundary message) in a conversation.
	GetPreviousPrivateMessages(context.Context, *GetPrivateMessagesRequest) (*GetPrivateMessagesResponse, error)
	// Retrieves next private messages (newer than the boundary message) in a conversation.
	GetNextPrivateMessages(context.Context, *GetPrivateMessagesRequest) (*GetPrivateMessagesResponse, error)
	// Updates the last read message pointer for a user in a private conversation.
	UpdateLastReadPrivateMessage(context.Context, *UpdateLastReadPrivateMessageRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedChatServiceServer()
}

// UnimplementedChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatServiceServer struct{}

func (UnimplementedChatServiceServer) CreateGroupMessage(context.Context, *CreateGroupMessageRequest) (*GroupMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroupMessage not implemented")
}
func (UnimplementedChatServiceServer) GetPreviousGroupMessages(context.Context, *GetGroupMessagesRequest) (*GetGroupMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPreviousGroupMessages not implemented")
}
func (UnimplementedChatServiceServer) GetNextGroupMessages(context.Context, *GetGroupMessagesRequest) (*GetGroupMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNextGroupMessages not implemented")
}
func (UnimplementedChatServiceServer) GetPrivateConversationById(context.Context, *GetPrivateConversationByIdRequest) (*PrivateConversationPreview, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPrivateConversationById not implemented")
}
func (UnimplementedChatServiceServer) GetPrivateConversations(context.Context, *GetPrivateConversationsRequest) (*GetPrivateConversationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPrivateConversations not implemented")
}
func (UnimplementedChatServiceServer) GetConvsWithUnreadsCount(context.Context, *GetConvsWithUnreadsCountRequest) (*GetConvsWithUnreadsCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConvsWithUnreadsCount not implemented")
}
func (UnimplementedChatServiceServer) CreatePrivateMessage(context.Context, *CreatePrivateMessageRequest) (*PrivateMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePrivateMessage not implemented")
}
func (UnimplementedChatServiceServer) GetPreviousPrivateMessages(context.Context, *GetPrivateMessagesRequest) (*GetPrivateMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPreviousPrivateMessages not implemented")
}
func (UnimplementedChatServiceServer) GetNextPrivateMessages(context.Context, *GetPrivateMessagesRequest) (*GetPrivateMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNextPrivateMessages not implemented")
}
func (UnimplementedChatServiceServer) UpdateLastReadPrivateMessage(context.Context, *UpdateLastReadPrivateMessageRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateLastReadPrivateMessage not implemented")
}
func (UnimplementedChatServiceServer) mustEmbedUnimplementedChatServiceServer() {}
func (UnimplementedChatServiceServer) testEmbeddedByValue()                     {}

// UnsafeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceServer will
// result in compilation errors.
type UnsafeChatServiceServer interface {
	mustEmbedUnimplementedChatServiceServer()
}

func RegisterChatServiceServer(s grpc.ServiceRegistrar, srv ChatServiceServer) {
	// If the following call panics, it indicates UnimplementedChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func _ChatService_CreateGroupMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).CreateGroupMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_CreateGroupMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).CreateGroupMessage(ctx, req.(*CreateGroupMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetPreviousGroupMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetPreviousGroupMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetPreviousGroupMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetPreviousGroupMessages(ctx, req.(*GetGroupMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetNextGroupMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetNextGroupMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetNextGroupMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetNextGroupMessages(ctx, req.(*GetGroupMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetPrivateConversationById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrivateConversationByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetPrivateConversationById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetPrivateConversationById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetPrivateConversationById(ctx, req.(*GetPrivateConversationByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetPrivateConversations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrivateConversationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetPrivateConversations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetPrivateConversations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetPrivateConversations(ctx, req.(*GetPrivateConversationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetConvsWithUnreadsCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConvsWithUnreadsCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetConvsWithUnreadsCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetConvsWithUnreadsCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetConvsWithUnreadsCount(ctx, req.(*GetConvsWithUnreadsCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_CreatePrivateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePrivateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).CreatePrivateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_CreatePrivateMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).CreatePrivateMessage(ctx, req.(*CreatePrivateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetPreviousPrivateMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrivateMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetPreviousPrivateMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetPreviousPrivateMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetPreviousPrivateMessages(ctx, req.(*GetPrivateMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetNextPrivateMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrivateMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetNextPrivateMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetNextPrivateMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetNextPrivateMessages(ctx, req.(*GetPrivateMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_UpdateLastReadPrivateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLastReadPrivateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).UpdateLastReadPrivateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_UpdateLastReadPrivateMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).UpdateLastReadPrivateMessage(ctx, req.(*UpdateLastReadPrivateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatService_ServiceDesc is the grpc.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGroupMessage",
			Handler:    _ChatService_CreateGroupMessage_Handler,
		},
		{
			MethodName: "GetPreviousGroupMessages",
			Handler:    _ChatService_GetPreviousGroupMessages_Handler,
		},
		{
			MethodName: "GetNextGroupMessages",
			Handler:    _ChatService_GetNextGroupMessages_Handler,
		},
		{
			MethodName: "GetPrivateConversationById",
			Handler:    _ChatService_GetPrivateConversationById_Handler,
		},
		{
			MethodName: "GetPrivateConversations",
			Handler:    _ChatService_GetPrivateConversations_Handler,
		},
		{
			MethodName: "GetConvsWithUnreadsCount",
			Handler:    _ChatService_GetConvsWithUnreadsCount_Handler,
		},
		{
			MethodName: "CreatePrivateMessage",
			Handler:    _ChatService_CreatePrivateMessage_Handler,
		},
		{
			MethodName: "GetPreviousPrivateMessages",
			Handler:    _ChatService_GetPreviousPrivateMessages_Handler,
		},
		{
			MethodName: "GetNextPrivateMessages",
			Handler:    _ChatService_GetNextPrivateMessages_Handler,
		},
		{
			MethodName: "UpdateLastReadPrivateMessage",
			Handler:    _ChatService_UpdateLastReadPrivateMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat.proto",
}
