// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: chat.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	common "social-network/shared/gen-go/common"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for creating a new group message.
// Contains the group ID, sender ID, and the text of the message.
type CreateGroupMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	SenderId      int64                  `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	MessageText   string                 `protobuf:"bytes,3,opt,name=message_text,json=messageText,proto3" json:"message_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupMessageRequest) Reset() {
	*x = CreateGroupMessageRequest{}
	mi := &file_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupMessageRequest) ProtoMessage() {}

func (x *CreateGroupMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupMessageRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupMessageRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGroupMessageRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CreateGroupMessageRequest) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *CreateGroupMessageRequest) GetMessageText() string {
	if x != nil {
		return x.MessageText
	}
	return ""
}

// Represents a group message in a conversation.
// Includes message ID, conversation ID, group ID, sender details, message text, and timestamps.
type GroupMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Sender        *common.User           `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	MessageText   string                 `protobuf:"bytes,4,opt,name=message_text,json=messageText,proto3" json:"message_text,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMessage) Reset() {
	*x = GroupMessage{}
	mi := &file_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMessage) ProtoMessage() {}

func (x *GroupMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMessage.ProtoReflect.Descriptor instead.
func (*GroupMessage) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

func (x *GroupMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupMessage) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupMessage) GetSender() *common.User {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *GroupMessage) GetMessageText() string {
	if x != nil {
		return x.MessageText
	}
	return ""
}

func (x *GroupMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GroupMessage) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GroupMessage) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

// Request message for retrieving group messages.
// Specifies the group ID, member ID, boundary message ID for pagination, and limit.
type GetGroupMessagesRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	GroupId           int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	MemberId          int64                  `protobuf:"varint,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	BoundaryMessageId int64                  `protobuf:"varint,3,opt,name=boundary_message_id,json=boundaryMessageId,proto3" json:"boundary_message_id,omitempty"`
	Limit             int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	RetrieveUsers     bool                   `protobuf:"varint,5,opt,name=retrieve_users,json=retrieveUsers,proto3" json:"retrieve_users,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetGroupMessagesRequest) Reset() {
	*x = GetGroupMessagesRequest{}
	mi := &file_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMessagesRequest) ProtoMessage() {}

func (x *GetGroupMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetGroupMessagesRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

func (x *GetGroupMessagesRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GetGroupMessagesRequest) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *GetGroupMessagesRequest) GetBoundaryMessageId() int64 {
	if x != nil {
		return x.BoundaryMessageId
	}
	return 0
}

func (x *GetGroupMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetGroupMessagesRequest) GetRetrieveUsers() bool {
	if x != nil {
		return x.RetrieveUsers
	}
	return false
}

// Response message for group messages retrieval.
// Indicates if there are more messages and contains the list of messages.
type GetGroupMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HaveMore      bool                   `protobuf:"varint,1,opt,name=have_more,json=haveMore,proto3" json:"have_more,omitempty"`
	Messages      []*GroupMessage        `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMessagesResponse) Reset() {
	*x = GetGroupMessagesResponse{}
	mi := &file_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMessagesResponse) ProtoMessage() {}

func (x *GetGroupMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetGroupMessagesResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{3}
}

func (x *GetGroupMessagesResponse) GetHaveMore() bool {
	if x != nil {
		return x.HaveMore
	}
	return false
}

func (x *GetGroupMessagesResponse) GetMessages() []*GroupMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// Request for retrieving a single conversation by id.
type GetPrivateConversationByIdRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId int64                  `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	InterlocutorId int64                  `protobuf:"varint,3,opt,name=interlocutor_id,json=interlocutorId,proto3" json:"interlocutor_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPrivateConversationByIdRequest) Reset() {
	*x = GetPrivateConversationByIdRequest{}
	mi := &file_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivateConversationByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivateConversationByIdRequest) ProtoMessage() {}

func (x *GetPrivateConversationByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivateConversationByIdRequest.ProtoReflect.Descriptor instead.
func (*GetPrivateConversationByIdRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{4}
}

func (x *GetPrivateConversationByIdRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetPrivateConversationByIdRequest) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *GetPrivateConversationByIdRequest) GetInterlocutorId() int64 {
	if x != nil {
		return x.InterlocutorId
	}
	return 0
}

// Request message for retrieving a paginated list of private conversations for a user.
// Includes user ID, date before which to fetch, and limit.
type GetPrivateConversationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BeforeDate    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=before_date,json=beforeDate,proto3" json:"before_date,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrivateConversationsRequest) Reset() {
	*x = GetPrivateConversationsRequest{}
	mi := &file_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivateConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivateConversationsRequest) ProtoMessage() {}

func (x *GetPrivateConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivateConversationsRequest.ProtoReflect.Descriptor instead.
func (*GetPrivateConversationsRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{5}
}

func (x *GetPrivateConversationsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetPrivateConversationsRequest) GetBeforeDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BeforeDate
	}
	return nil
}

func (x *GetPrivateConversationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Preview of a private conversation.
// Includes conversation ID, last update time, interlocutor,
// last message, and unread count.
type PrivateConversationPreview struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId int64                  `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Interlocutor   *common.User           `protobuf:"bytes,3,opt,name=interlocutor,proto3" json:"interlocutor,omitempty"`
	LastMessage    *PrivateMessage        `protobuf:"bytes,4,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`
	UnreadCount    int32                  `protobuf:"varint,5,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrivateConversationPreview) Reset() {
	*x = PrivateConversationPreview{}
	mi := &file_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateConversationPreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateConversationPreview) ProtoMessage() {}

func (x *PrivateConversationPreview) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateConversationPreview.ProtoReflect.Descriptor instead.
func (*PrivateConversationPreview) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{6}
}

func (x *PrivateConversationPreview) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *PrivateConversationPreview) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *PrivateConversationPreview) GetInterlocutor() *common.User {
	if x != nil {
		return x.Interlocutor
	}
	return nil
}

func (x *PrivateConversationPreview) GetLastMessage() *PrivateMessage {
	if x != nil {
		return x.LastMessage
	}
	return nil
}

func (x *PrivateConversationPreview) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

// Response message for private conversations retrieval.
// Contains a list of conversation previews.
type GetPrivateConversationsResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Conversations []*PrivateConversationPreview `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrivateConversationsResponse) Reset() {
	*x = GetPrivateConversationsResponse{}
	mi := &file_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivateConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivateConversationsResponse) ProtoMessage() {}

func (x *GetPrivateConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivateConversationsResponse.ProtoReflect.Descriptor instead.
func (*GetPrivateConversationsResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{7}
}

func (x *GetPrivateConversationsResponse) GetConversations() []*PrivateConversationPreview {
	if x != nil {
		return x.Conversations
	}
	return nil
}

// Request to get conversation count that user has unread messages
type GetConvsWithUnreadsCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConvsWithUnreadsCountRequest) Reset() {
	*x = GetConvsWithUnreadsCountRequest{}
	mi := &file_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConvsWithUnreadsCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConvsWithUnreadsCountRequest) ProtoMessage() {}

func (x *GetConvsWithUnreadsCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConvsWithUnreadsCountRequest.ProtoReflect.Descriptor instead.
func (*GetConvsWithUnreadsCountRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{8}
}

func (x *GetConvsWithUnreadsCountRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Count of conversations with unread messages
type GetConvsWithUnreadsCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConvsWithUnreadsCountResponse) Reset() {
	*x = GetConvsWithUnreadsCountResponse{}
	mi := &file_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConvsWithUnreadsCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConvsWithUnreadsCountResponse) ProtoMessage() {}

func (x *GetConvsWithUnreadsCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConvsWithUnreadsCountResponse.ProtoReflect.Descriptor instead.
func (*GetConvsWithUnreadsCountResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{9}
}

func (x *GetConvsWithUnreadsCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Request message for creating a new private message.
// Contains sender ID, interlocutor ID, and message text.
type CreatePrivateMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SenderId       int64                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	InterlocutorId int64                  `protobuf:"varint,2,opt,name=interlocutor_id,json=interlocutorId,proto3" json:"interlocutor_id,omitempty"`
	MessageText    string                 `protobuf:"bytes,3,opt,name=message_text,json=messageText,proto3" json:"message_text,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePrivateMessageRequest) Reset() {
	*x = CreatePrivateMessageRequest{}
	mi := &file_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePrivateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePrivateMessageRequest) ProtoMessage() {}

func (x *CreatePrivateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePrivateMessageRequest.ProtoReflect.Descriptor instead.
func (*CreatePrivateMessageRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{10}
}

func (x *CreatePrivateMessageRequest) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *CreatePrivateMessageRequest) GetInterlocutorId() int64 {
	if x != nil {
		return x.InterlocutorId
	}
	return 0
}

func (x *CreatePrivateMessageRequest) GetMessageText() string {
	if x != nil {
		return x.MessageText
	}
	return ""
}

// Represents a private message in a conversation.
// Includes message ID, conversation ID, sender, receiver ID, message text, and timestamps.
type PrivateMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ConversationId int64                  `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Sender         *common.User           `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	ReceiverId     int64                  `protobuf:"varint,4,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	MessageText    string                 `protobuf:"bytes,5,opt,name=message_text,json=messageText,proto3" json:"message_text,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrivateMessage) Reset() {
	*x = PrivateMessage{}
	mi := &file_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateMessage) ProtoMessage() {}

func (x *PrivateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateMessage.ProtoReflect.Descriptor instead.
func (*PrivateMessage) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{11}
}

func (x *PrivateMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PrivateMessage) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *PrivateMessage) GetSender() *common.User {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *PrivateMessage) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *PrivateMessage) GetMessageText() string {
	if x != nil {
		return x.MessageText
	}
	return ""
}

func (x *PrivateMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PrivateMessage) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *PrivateMessage) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

// Request message for retrieving private messages.
// Specifies conversation ID, user ID, boundary message ID for pagination, limit, and user retrieval flag.
type GetPrivateMessagesRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	InterlocutorId    int64                  `protobuf:"varint,2,opt,name=interlocutor_id,json=interlocutorId,proto3" json:"interlocutor_id,omitempty"`
	BoundaryMessageId int64                  `protobuf:"varint,3,opt,name=boundary_message_id,json=boundaryMessageId,proto3" json:"boundary_message_id,omitempty"`
	Limit             int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	RetrieveUsers     bool                   `protobuf:"varint,5,opt,name=retrieve_users,json=retrieveUsers,proto3" json:"retrieve_users,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetPrivateMessagesRequest) Reset() {
	*x = GetPrivateMessagesRequest{}
	mi := &file_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivateMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivateMessagesRequest) ProtoMessage() {}

func (x *GetPrivateMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivateMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetPrivateMessagesRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{12}
}

func (x *GetPrivateMessagesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetPrivateMessagesRequest) GetInterlocutorId() int64 {
	if x != nil {
		return x.InterlocutorId
	}
	return 0
}

func (x *GetPrivateMessagesRequest) GetBoundaryMessageId() int64 {
	if x != nil {
		return x.BoundaryMessageId
	}
	return 0
}

func (x *GetPrivateMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetPrivateMessagesRequest) GetRetrieveUsers() bool {
	if x != nil {
		return x.RetrieveUsers
	}
	return false
}

// Response message for private messages retrieval.
// Indicates if there are more messages and contains the list of messages.
type GetPrivateMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HaveMore      bool                   `protobuf:"varint,1,opt,name=have_more,json=haveMore,proto3" json:"have_more,omitempty"`
	Messages      []*PrivateMessage      `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrivateMessagesResponse) Reset() {
	*x = GetPrivateMessagesResponse{}
	mi := &file_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivateMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivateMessagesResponse) ProtoMessage() {}

func (x *GetPrivateMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivateMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetPrivateMessagesResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{13}
}

func (x *GetPrivateMessagesResponse) GetHaveMore() bool {
	if x != nil {
		return x.HaveMore
	}
	return false
}

func (x *GetPrivateMessagesResponse) GetMessages() []*PrivateMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// Request message to update the last read message in a private conversation.
// Contains conversation ID, user ID, and last read message ID.
type UpdateLastReadPrivateMessageRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConversationId    int64                  `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId            int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LastReadMessageId int64                  `protobuf:"varint,3,opt,name=last_read_message_id,json=lastReadMessageId,proto3" json:"last_read_message_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateLastReadPrivateMessageRequest) Reset() {
	*x = UpdateLastReadPrivateMessageRequest{}
	mi := &file_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLastReadPrivateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLastReadPrivateMessageRequest) ProtoMessage() {}

func (x *UpdateLastReadPrivateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLastReadPrivateMessageRequest.ProtoReflect.Descriptor instead.
func (*UpdateLastReadPrivateMessageRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateLastReadPrivateMessageRequest) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *UpdateLastReadPrivateMessageRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateLastReadPrivateMessageRequest) GetLastReadMessageId() int64 {
	if x != nil {
		return x.LastReadMessageId
	}
	return 0
}

var File_chat_proto protoreflect.FileDescriptor

const file_chat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"chat.proto\x12\x04chat\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\fcommon.proto\"v\n" +
	"\x19CreateGroupMessageRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\x03R\bsenderId\x12!\n" +
	"\fmessage_text\x18\x03 \x01(\tR\vmessageText\"\xb3\x02\n" +
	"\fGroupMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\x12$\n" +
	"\x06sender\x18\x03 \x01(\v2\f.common.UserR\x06sender\x12!\n" +
	"\fmessage_text\x18\x04 \x01(\tR\vmessageText\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\xbe\x01\n" +
	"\x17GetGroupMessagesRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\x03R\bmemberId\x12.\n" +
	"\x13boundary_message_id\x18\x03 \x01(\x03R\x11boundaryMessageId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12%\n" +
	"\x0eretrieve_users\x18\x05 \x01(\bR\rretrieveUsers\"g\n" +
	"\x18GetGroupMessagesResponse\x12\x1b\n" +
	"\thave_more\x18\x01 \x01(\bR\bhaveMore\x12.\n" +
	"\bmessages\x18\x02 \x03(\v2\x12.chat.GroupMessageR\bmessages\"\x8e\x01\n" +
	"!GetPrivateConversationByIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x03R\x0econversationId\x12'\n" +
	"\x0finterlocutor_id\x18\x03 \x01(\x03R\x0einterlocutorId\"\x8c\x01\n" +
	"\x1eGetPrivateConversationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12;\n" +
	"\vbefore_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"beforeDate\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x8e\x02\n" +
	"\x1aPrivateConversationPreview\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03R\x0econversationId\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x120\n" +
	"\finterlocutor\x18\x03 \x01(\v2\f.common.UserR\finterlocutor\x127\n" +
	"\flast_message\x18\x04 \x01(\v2\x14.chat.PrivateMessageR\vlastMessage\x12!\n" +
	"\funread_count\x18\x05 \x01(\x05R\vunreadCount\"i\n" +
	"\x1fGetPrivateConversationsResponse\x12F\n" +
	"\rconversations\x18\x01 \x03(\v2 .chat.PrivateConversationPreviewR\rconversations\":\n" +
	"\x1fGetConvsWithUnreadsCountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"8\n" +
	" GetConvsWithUnreadsCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"\x86\x01\n" +
	"\x1bCreatePrivateMessageRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x03R\bsenderId\x12'\n" +
	"\x0finterlocutor_id\x18\x02 \x01(\x03R\x0einterlocutorId\x12!\n" +
	"\fmessage_text\x18\x03 \x01(\tR\vmessageText\"\xe4\x02\n" +
	"\x0ePrivateMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x03R\x0econversationId\x12$\n" +
	"\x06sender\x18\x03 \x01(\v2\f.common.UserR\x06sender\x12\x1f\n" +
	"\vreceiver_id\x18\x04 \x01(\x03R\n" +
	"receiverId\x12!\n" +
	"\fmessage_text\x18\x05 \x01(\tR\vmessageText\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\xca\x01\n" +
	"\x19GetPrivateMessagesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12'\n" +
	"\x0finterlocutor_id\x18\x02 \x01(\x03R\x0einterlocutorId\x12.\n" +
	"\x13boundary_message_id\x18\x03 \x01(\x03R\x11boundaryMessageId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12%\n" +
	"\x0eretrieve_users\x18\x05 \x01(\bR\rretrieveUsers\"k\n" +
	"\x1aGetPrivateMessagesResponse\x12\x1b\n" +
	"\thave_more\x18\x01 \x01(\bR\bhaveMore\x120\n" +
	"\bmessages\x18\x02 \x03(\v2\x14.chat.PrivateMessageR\bmessages\"\x98\x01\n" +
	"#UpdateLastReadPrivateMessageRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03R\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12/\n" +
	"\x14last_read_message_id\x18\x03 \x01(\x03R\x11lastReadMessageId2\xb8\a\n" +
	"\vChatService\x12I\n" +
	"\x12CreateGroupMessage\x12\x1f.chat.CreateGroupMessageRequest\x1a\x12.chat.GroupMessage\x12Y\n" +
	"\x18GetPreviousGroupMessages\x12\x1d.chat.GetGroupMessagesRequest\x1a\x1e.chat.GetGroupMessagesResponse\x12U\n" +
	"\x14GetNextGroupMessages\x12\x1d.chat.GetGroupMessagesRequest\x1a\x1e.chat.GetGroupMessagesResponse\x12g\n" +
	"\x1aGetPrivateConversationById\x12'.chat.GetPrivateConversationByIdRequest\x1a .chat.PrivateConversationPreview\x12f\n" +
	"\x17GetPrivateConversations\x12$.chat.GetPrivateConversationsRequest\x1a%.chat.GetPrivateConversationsResponse\x12i\n" +
	"\x18GetConvsWithUnreadsCount\x12%.chat.GetConvsWithUnreadsCountRequest\x1a&.chat.GetConvsWithUnreadsCountResponse\x12O\n" +
	"\x14CreatePrivateMessage\x12!.chat.CreatePrivateMessageRequest\x1a\x14.chat.PrivateMessage\x12_\n" +
	"\x1aGetPreviousPrivateMessages\x12\x1f.chat.GetPrivateMessagesRequest\x1a .chat.GetPrivateMessagesResponse\x12[\n" +
	"\x16GetNextPrivateMessages\x12\x1f.chat.GetPrivateMessagesRequest\x1a .chat.GetPrivateMessagesResponse\x12a\n" +
	"\x1cUpdateLastReadPrivateMessage\x12).chat.UpdateLastReadPrivateMessageRequest\x1a\x16.google.protobuf.EmptyB(Z&social-network/shared/gen-go/chat;chatb\x06proto3"

var (
	file_chat_proto_rawDescOnce sync.Once
	file_chat_proto_rawDescData []byte
)

func file_chat_proto_rawDescGZIP() []byte {
	file_chat_proto_rawDescOnce.Do(func() {
		file_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)))
	})
	return file_chat_proto_rawDescData
}

var file_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_chat_proto_goTypes = []any{
	(*CreateGroupMessageRequest)(nil),           // 0: chat.CreateGroupMessageRequest
	(*GroupMessage)(nil),                        // 1: chat.GroupMessage
	(*GetGroupMessagesRequest)(nil),             // 2: chat.GetGroupMessagesRequest
	(*GetGroupMessagesResponse)(nil),            // 3: chat.GetGroupMessagesResponse
	(*GetPrivateConversationByIdRequest)(nil),   // 4: chat.GetPrivateConversationByIdRequest
	(*GetPrivateConversationsRequest)(nil),      // 5: chat.GetPrivateConversationsRequest
	(*PrivateConversationPreview)(nil),          // 6: chat.PrivateConversationPreview
	(*GetPrivateConversationsResponse)(nil),     // 7: chat.GetPrivateConversationsResponse
	(*GetConvsWithUnreadsCountRequest)(nil),     // 8: chat.GetConvsWithUnreadsCountRequest
	(*GetConvsWithUnreadsCountResponse)(nil),    // 9: chat.GetConvsWithUnreadsCountResponse
	(*CreatePrivateMessageRequest)(nil),         // 10: chat.CreatePrivateMessageRequest
	(*PrivateMessage)(nil),                      // 11: chat.PrivateMessage
	(*GetPrivateMessagesRequest)(nil),           // 12: chat.GetPrivateMessagesRequest
	(*GetPrivateMessagesResponse)(nil),          // 13: chat.GetPrivateMessagesResponse
	(*UpdateLastReadPrivateMessageRequest)(nil), // 14: chat.UpdateLastReadPrivateMessageRequest
	(*common.User)(nil),                         // 15: common.User
	(*timestamppb.Timestamp)(nil),               // 16: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                       // 17: google.protobuf.Empty
}
var file_chat_proto_depIdxs = []int32{
	15, // 0: chat.GroupMessage.sender:type_name -> common.User
	16, // 1: chat.GroupMessage.created_at:type_name -> google.protobuf.Timestamp
	16, // 2: chat.GroupMessage.updated_at:type_name -> google.protobuf.Timestamp
	16, // 3: chat.GroupMessage.deleted_at:type_name -> google.protobuf.Timestamp
	1,  // 4: chat.GetGroupMessagesResponse.messages:type_name -> chat.GroupMessage
	16, // 5: chat.GetPrivateConversationsRequest.before_date:type_name -> google.protobuf.Timestamp
	16, // 6: chat.PrivateConversationPreview.updated_at:type_name -> google.protobuf.Timestamp
	15, // 7: chat.PrivateConversationPreview.interlocutor:type_name -> common.User
	11, // 8: chat.PrivateConversationPreview.last_message:type_name -> chat.PrivateMessage
	6,  // 9: chat.GetPrivateConversationsResponse.conversations:type_name -> chat.PrivateConversationPreview
	15, // 10: chat.PrivateMessage.sender:type_name -> common.User
	16, // 11: chat.PrivateMessage.created_at:type_name -> google.protobuf.Timestamp
	16, // 12: chat.PrivateMessage.updated_at:type_name -> google.protobuf.Timestamp
	16, // 13: chat.PrivateMessage.deleted_at:type_name -> google.protobuf.Timestamp
	11, // 14: chat.GetPrivateMessagesResponse.messages:type_name -> chat.PrivateMessage
	0,  // 15: chat.ChatService.CreateGroupMessage:input_type -> chat.CreateGroupMessageRequest
	2,  // 16: chat.ChatService.GetPreviousGroupMessages:input_type -> chat.GetGroupMessagesRequest
	2,  // 17: chat.ChatService.GetNextGroupMessages:input_type -> chat.GetGroupMessagesRequest
	4,  // 18: chat.ChatService.GetPrivateConversationById:input_type -> chat.GetPrivateConversationByIdRequest
	5,  // 19: chat.ChatService.GetPrivateConversations:input_type -> chat.GetPrivateConversationsRequest
	8,  // 20: chat.ChatService.GetConvsWithUnreadsCount:input_type -> chat.GetConvsWithUnreadsCountRequest
	10, // 21: chat.ChatService.CreatePrivateMessage:input_type -> chat.CreatePrivateMessageRequest
	12, // 22: chat.ChatService.GetPreviousPrivateMessages:input_type -> chat.GetPrivateMessagesRequest
	12, // 23: chat.ChatService.GetNextPrivateMessages:input_type -> chat.GetPrivateMessagesRequest
	14, // 24: chat.ChatService.UpdateLastReadPrivateMessage:input_type -> chat.UpdateLastReadPrivateMessageRequest
	1,  // 25: chat.ChatService.CreateGroupMessage:output_type -> chat.GroupMessage
	3,  // 26: chat.ChatService.GetPreviousGroupMessages:output_type -> chat.GetGroupMessagesResponse
	3,  // 27: chat.ChatService.GetNextGroupMessages:output_type -> chat.GetGroupMessagesResponse
	6,  // 28: chat.ChatService.GetPrivateConversationById:output_type -> chat.PrivateConversationPreview
	7,  // 29: chat.ChatService.GetPrivateConversations:output_type -> chat.GetPrivateConversationsResponse
	9,  // 30: chat.ChatService.GetConvsWithUnreadsCount:output_type -> chat.GetConvsWithUnreadsCountResponse
	11, // 31: chat.ChatService.CreatePrivateMessage:output_type -> chat.PrivateMessage
	13, // 32: chat.ChatService.GetPreviousPrivateMessages:output_type -> chat.GetPrivateMessagesResponse
	13, // 33: chat.ChatService.GetNextPrivateMessages:output_type -> chat.GetPrivateMessagesResponse
	17, // 34: chat.ChatService.UpdateLastReadPrivateMessage:output_type -> google.protobuf.Empty
	25, // [25:35] is the sub-list for method output_type
	15, // [15:25] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_chat_proto_init() }
func file_chat_proto_init() {
	if File_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_proto_goTypes,
		DependencyIndexes: file_chat_proto_depIdxs,
		MessageInfos:      file_chat_proto_msgTypes,
	}.Build()
	File_chat_proto = out.File
	file_chat_proto_goTypes = nil
	file_chat_proto_depIdxs = nil
}
