// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: media.proto

package media

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Describes the type of file
// original, thumb, small, medium, large, original
type FileVariant int32

const (
	FileVariant_IMG_VARIANT_UNSPECIFIED FileVariant = 0 // Default unspecified variant
	FileVariant_THUMBNAIL               FileVariant = 1 // Thumbnail size variant
	FileVariant_SMALL                   FileVariant = 2 // Small size variant
	FileVariant_MEDIUM                  FileVariant = 3 // Medium size variant
	FileVariant_LARGE                   FileVariant = 4 // Large size variant
	FileVariant_ORIGINAL                FileVariant = 5 // Original size variant
)

// Enum value maps for FileVariant.
var (
	FileVariant_name = map[int32]string{
		0: "IMG_VARIANT_UNSPECIFIED",
		1: "THUMBNAIL",
		2: "SMALL",
		3: "MEDIUM",
		4: "LARGE",
		5: "ORIGINAL",
	}
	FileVariant_value = map[string]int32{
		"IMG_VARIANT_UNSPECIFIED": 0,
		"THUMBNAIL":               1,
		"SMALL":                   2,
		"MEDIUM":                  3,
		"LARGE":                   4,
		"ORIGINAL":                5,
	}
)

func (x FileVariant) Enum() *FileVariant {
	p := new(FileVariant)
	*p = x
	return p
}

func (x FileVariant) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileVariant) Descriptor() protoreflect.EnumDescriptor {
	return file_media_proto_enumTypes[0].Descriptor()
}

func (FileVariant) Type() protoreflect.EnumType {
	return &file_media_proto_enumTypes[0]
}

func (x FileVariant) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileVariant.Descriptor instead.
func (FileVariant) EnumDescriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{0}
}

// Describes file visibility
// private, public
type FileVisibility int32

const (
	FileVisibility_FILE_VISIBILITY_UNSPECIFIED FileVisibility = 0 // Default unspecified visibility
	FileVisibility_PRIVATE                     FileVisibility = 1 // Private file visibility
	FileVisibility_PUBLIC                      FileVisibility = 2 // Public file visibility
)

// Enum value maps for FileVisibility.
var (
	FileVisibility_name = map[int32]string{
		0: "FILE_VISIBILITY_UNSPECIFIED",
		1: "PRIVATE",
		2: "PUBLIC",
	}
	FileVisibility_value = map[string]int32{
		"FILE_VISIBILITY_UNSPECIFIED": 0,
		"PRIVATE":                     1,
		"PUBLIC":                      2,
	}
)

func (x FileVisibility) Enum() *FileVisibility {
	p := new(FileVisibility)
	*p = x
	return p
}

func (x FileVisibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileVisibility) Descriptor() protoreflect.EnumDescriptor {
	return file_media_proto_enumTypes[1].Descriptor()
}

func (FileVisibility) Type() protoreflect.EnumType {
	return &file_media_proto_enumTypes[1]
}

func (x FileVisibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileVisibility.Descriptor instead.
func (FileVisibility) EnumDescriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{1}
}

// Describes the file upload status:
// pending, processing, complete, failed
type UploadStatus int32

const (
	UploadStatus_UPLOAD_STATUS_UNSPECIFIED UploadStatus = 0
	UploadStatus_UPLOAD_STATUS_PENDING     UploadStatus = 1
	UploadStatus_UPLOAD_STATUS_PROCESSING  UploadStatus = 2
	UploadStatus_UPLOAD_STATUS_COMPLETE    UploadStatus = 3
	UploadStatus_UPLOAD_STATUS_FAILED      UploadStatus = 4
)

// Enum value maps for UploadStatus.
var (
	UploadStatus_name = map[int32]string{
		0: "UPLOAD_STATUS_UNSPECIFIED",
		1: "UPLOAD_STATUS_PENDING",
		2: "UPLOAD_STATUS_PROCESSING",
		3: "UPLOAD_STATUS_COMPLETE",
		4: "UPLOAD_STATUS_FAILED",
	}
	UploadStatus_value = map[string]int32{
		"UPLOAD_STATUS_UNSPECIFIED": 0,
		"UPLOAD_STATUS_PENDING":     1,
		"UPLOAD_STATUS_PROCESSING":  2,
		"UPLOAD_STATUS_COMPLETE":    3,
		"UPLOAD_STATUS_FAILED":      4,
	}
)

func (x UploadStatus) Enum() *UploadStatus {
	p := new(UploadStatus)
	*p = x
	return p
}

func (x UploadStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UploadStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_media_proto_enumTypes[2].Descriptor()
}

func (UploadStatus) Type() protoreflect.EnumType {
	return &file_media_proto_enumTypes[2]
}

func (x UploadStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UploadStatus.Descriptor instead.
func (UploadStatus) EnumDescriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{2}
}

// Request message for uploading an image
type UploadImageRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Filename          string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"` // Metadata of the file to upload
	MimeType          string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	SizeBytes         int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Visibility        FileVisibility         `protobuf:"varint,4,opt,name=visibility,proto3,enum=media.FileVisibility" json:"visibility,omitempty"`
	ExpirationSeconds int64                  `protobuf:"varint,5,opt,name=expiration_seconds,json=expirationSeconds,proto3" json:"expiration_seconds,omitempty"` // Expiration time for the upload URL in seconds
	Variants          []FileVariant          `protobuf:"varint,6,rep,packed,name=variants,proto3,enum=media.FileVariant" json:"variants,omitempty"`              // List of image variants to generate
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UploadImageRequest) Reset() {
	*x = UploadImageRequest{}
	mi := &file_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageRequest) ProtoMessage() {}

func (x *UploadImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageRequest.ProtoReflect.Descriptor instead.
func (*UploadImageRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{0}
}

func (x *UploadImageRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadImageRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *UploadImageRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *UploadImageRequest) GetVisibility() FileVisibility {
	if x != nil {
		return x.Visibility
	}
	return FileVisibility_FILE_VISIBILITY_UNSPECIFIED
}

func (x *UploadImageRequest) GetExpirationSeconds() int64 {
	if x != nil {
		return x.ExpirationSeconds
	}
	return 0
}

func (x *UploadImageRequest) GetVariants() []FileVariant {
	if x != nil {
		return x.Variants
	}
	return nil
}

// Response message for uploading an image
type UploadImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        int64                  `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`         // Unique identifier of the uploaded file
	UploadUrl     string                 `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"` // Pre-signed URL for uploading the file
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageResponse) Reset() {
	*x = UploadImageResponse{}
	mi := &file_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageResponse) ProtoMessage() {}

func (x *UploadImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageResponse.ProtoReflect.Descriptor instead.
func (*UploadImageResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{1}
}

func (x *UploadImageResponse) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *UploadImageResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

// Request message for retrieving an image
type GetImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       int64                  `protobuf:"varint,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`         // Unique identifier of the image
	Variant       FileVariant            `protobuf:"varint,2,opt,name=variant,proto3,enum=media.FileVariant" json:"variant,omitempty"` // Desired variant of the image
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageRequest) Reset() {
	*x = GetImageRequest{}
	mi := &file_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageRequest) ProtoMessage() {}

func (x *GetImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageRequest.ProtoReflect.Descriptor instead.
func (*GetImageRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{2}
}

func (x *GetImageRequest) GetImageId() int64 {
	if x != nil {
		return x.ImageId
	}
	return 0
}

func (x *GetImageRequest) GetVariant() FileVariant {
	if x != nil {
		return x.Variant
	}
	return FileVariant_IMG_VARIANT_UNSPECIFIED
}

// Response message for retrieving an image
type GetImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DownloadUrl   string                 `protobuf:"bytes,1,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"` // Pre-signed URL for downloading the image
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageResponse) Reset() {
	*x = GetImageResponse{}
	mi := &file_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageResponse) ProtoMessage() {}

func (x *GetImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageResponse.ProtoReflect.Descriptor instead.
func (*GetImageResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{3}
}

func (x *GetImageResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

// Request message for validating an upload
type ValidateUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        int64                  `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`          // Metadata of the upload to validate
	ReturnUrl     bool                   `protobuf:"varint,2,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"` // Request download url after validation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateUploadRequest) Reset() {
	*x = ValidateUploadRequest{}
	mi := &file_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateUploadRequest) ProtoMessage() {}

func (x *ValidateUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateUploadRequest.ProtoReflect.Descriptor instead.
func (*ValidateUploadRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateUploadRequest) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *ValidateUploadRequest) GetReturnUrl() bool {
	if x != nil {
		return x.ReturnUrl
	}
	return false
}

// Response on validate upload containing download url only if requested
type ValidateUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DownloadUrl   string                 `protobuf:"bytes,1,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"` // Pre-signed URL for downloading the image
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateUploadResponse) Reset() {
	*x = ValidateUploadResponse{}
	mi := &file_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateUploadResponse) ProtoMessage() {}

func (x *ValidateUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateUploadResponse.ProtoReflect.Descriptor instead.
func (*ValidateUploadResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateUploadResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

type ImageIds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImgIds        []int64                `protobuf:"varint,1,rep,packed,name=img_ids,json=imgIds,proto3" json:"img_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageIds) Reset() {
	*x = ImageIds{}
	mi := &file_media_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageIds) ProtoMessage() {}

func (x *ImageIds) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageIds.ProtoReflect.Descriptor instead.
func (*ImageIds) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{6}
}

func (x *ImageIds) GetImgIds() []int64 {
	if x != nil {
		return x.ImgIds
	}
	return nil
}

// Request with an array of file ids and the prefered variant.
// Variant is common for all ids. If a variant is not present
// returns the original.
type GetImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImgIds        *ImageIds              `protobuf:"bytes,1,opt,name=img_ids,json=imgIds,proto3" json:"img_ids,omitempty"`
	Variant       FileVariant            `protobuf:"varint,2,opt,name=variant,proto3,enum=media.FileVariant" json:"variant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImagesRequest) Reset() {
	*x = GetImagesRequest{}
	mi := &file_media_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImagesRequest) ProtoMessage() {}

func (x *GetImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImagesRequest.ProtoReflect.Descriptor instead.
func (*GetImagesRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{7}
}

func (x *GetImagesRequest) GetImgIds() *ImageIds {
	if x != nil {
		return x.ImgIds
	}
	return nil
}

func (x *GetImagesRequest) GetVariant() FileVariant {
	if x != nil {
		return x.Variant
	}
	return FileVariant_IMG_VARIANT_UNSPECIFIED
}

// Pair of file id and upload status representing the files that
// not marked as completed.
type FailedId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        int64                  `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Status        UploadStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=media.UploadStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailedId) Reset() {
	*x = FailedId{}
	mi := &file_media_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailedId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailedId) ProtoMessage() {}

func (x *FailedId) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailedId.ProtoReflect.Descriptor instead.
func (*FailedId) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{8}
}

func (x *FailedId) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *FailedId) GetStatus() UploadStatus {
	if x != nil {
		return x.Status
	}
	return UploadStatus_UPLOAD_STATUS_UNSPECIFIED
}

// map of image ids and dowload urls and array of failed ids.
type GetImagesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// map[ct.Id]string
	DownloadUrls map[int64]string `protobuf:"bytes,1,rep,name=download_urls,json=downloadUrls,proto3" json:"download_urls,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// []FailedId
	FailedIds     []*FailedId `protobuf:"bytes,2,rep,name=failed_ids,json=failedIds,proto3" json:"failed_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImagesResponse) Reset() {
	*x = GetImagesResponse{}
	mi := &file_media_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImagesResponse) ProtoMessage() {}

func (x *GetImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImagesResponse.ProtoReflect.Descriptor instead.
func (*GetImagesResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{9}
}

func (x *GetImagesResponse) GetDownloadUrls() map[int64]string {
	if x != nil {
		return x.DownloadUrls
	}
	return nil
}

func (x *GetImagesResponse) GetFailedIds() []*FailedId {
	if x != nil {
		return x.FailedIds
	}
	return nil
}

var File_media_proto protoreflect.FileDescriptor

const file_media_proto_rawDesc = "" +
	"\n" +
	"\vmedia.proto\x12\x05media\x1a\x1bgoogle/protobuf/empty.proto\"\x82\x02\n" +
	"\x12UploadImageRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x125\n" +
	"\n" +
	"visibility\x18\x04 \x01(\x0e2\x15.media.FileVisibilityR\n" +
	"visibility\x12-\n" +
	"\x12expiration_seconds\x18\x05 \x01(\x03R\x11expirationSeconds\x12.\n" +
	"\bvariants\x18\x06 \x03(\x0e2\x12.media.FileVariantR\bvariants\"M\n" +
	"\x13UploadImageResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\x03R\x06fileId\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\"Z\n" +
	"\x0fGetImageRequest\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\x03R\aimageId\x12,\n" +
	"\avariant\x18\x02 \x01(\x0e2\x12.media.FileVariantR\avariant\"5\n" +
	"\x10GetImageResponse\x12!\n" +
	"\fdownload_url\x18\x01 \x01(\tR\vdownloadUrl\"O\n" +
	"\x15ValidateUploadRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\x03R\x06fileId\x12\x1d\n" +
	"\n" +
	"return_url\x18\x02 \x01(\bR\treturnUrl\";\n" +
	"\x16ValidateUploadResponse\x12!\n" +
	"\fdownload_url\x18\x01 \x01(\tR\vdownloadUrl\"#\n" +
	"\bImageIds\x12\x17\n" +
	"\aimg_ids\x18\x01 \x03(\x03R\x06imgIds\"j\n" +
	"\x10GetImagesRequest\x12(\n" +
	"\aimg_ids\x18\x01 \x01(\v2\x0f.media.ImageIdsR\x06imgIds\x12,\n" +
	"\avariant\x18\x02 \x01(\x0e2\x12.media.FileVariantR\avariant\"P\n" +
	"\bFailedId\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\x03R\x06fileId\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.media.UploadStatusR\x06status\"\xd5\x01\n" +
	"\x11GetImagesResponse\x12O\n" +
	"\rdownload_urls\x18\x01 \x03(\v2*.media.GetImagesResponse.DownloadUrlsEntryR\fdownloadUrls\x12.\n" +
	"\n" +
	"failed_ids\x18\x02 \x03(\v2\x0f.media.FailedIdR\tfailedIds\x1a?\n" +
	"\x11DownloadUrlsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*i\n" +
	"\vFileVariant\x12\x1b\n" +
	"\x17IMG_VARIANT_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tTHUMBNAIL\x10\x01\x12\t\n" +
	"\x05SMALL\x10\x02\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x03\x12\t\n" +
	"\x05LARGE\x10\x04\x12\f\n" +
	"\bORIGINAL\x10\x05*J\n" +
	"\x0eFileVisibility\x12\x1f\n" +
	"\x1bFILE_VISIBILITY_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPRIVATE\x10\x01\x12\n" +
	"\n" +
	"\x06PUBLIC\x10\x02*\x9c\x01\n" +
	"\fUploadStatus\x12\x1d\n" +
	"\x19UPLOAD_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15UPLOAD_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18UPLOAD_STATUS_PROCESSING\x10\x02\x12\x1a\n" +
	"\x16UPLOAD_STATUS_COMPLETE\x10\x03\x12\x18\n" +
	"\x14UPLOAD_STATUS_FAILED\x10\x042\xa0\x02\n" +
	"\fMediaService\x12D\n" +
	"\vUploadImage\x12\x19.media.UploadImageRequest\x1a\x1a.media.UploadImageResponse\x12;\n" +
	"\bGetImage\x12\x16.media.GetImageRequest\x1a\x17.media.GetImageResponse\x12>\n" +
	"\tGetImages\x12\x17.media.GetImagesRequest\x1a\x18.media.GetImagesResponse\x12M\n" +
	"\x0eValidateUpload\x12\x1c.media.ValidateUploadRequest\x1a\x1d.media.ValidateUploadResponseB*Z(social-network/shared/gen-go/media;mediab\x06proto3"

var (
	file_media_proto_rawDescOnce sync.Once
	file_media_proto_rawDescData []byte
)

func file_media_proto_rawDescGZIP() []byte {
	file_media_proto_rawDescOnce.Do(func() {
		file_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_proto_rawDesc), len(file_media_proto_rawDesc)))
	})
	return file_media_proto_rawDescData
}

var file_media_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_media_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_media_proto_goTypes = []any{
	(FileVariant)(0),               // 0: media.FileVariant
	(FileVisibility)(0),            // 1: media.FileVisibility
	(UploadStatus)(0),              // 2: media.UploadStatus
	(*UploadImageRequest)(nil),     // 3: media.UploadImageRequest
	(*UploadImageResponse)(nil),    // 4: media.UploadImageResponse
	(*GetImageRequest)(nil),        // 5: media.GetImageRequest
	(*GetImageResponse)(nil),       // 6: media.GetImageResponse
	(*ValidateUploadRequest)(nil),  // 7: media.ValidateUploadRequest
	(*ValidateUploadResponse)(nil), // 8: media.ValidateUploadResponse
	(*ImageIds)(nil),               // 9: media.ImageIds
	(*GetImagesRequest)(nil),       // 10: media.GetImagesRequest
	(*FailedId)(nil),               // 11: media.FailedId
	(*GetImagesResponse)(nil),      // 12: media.GetImagesResponse
	nil,                            // 13: media.GetImagesResponse.DownloadUrlsEntry
}
var file_media_proto_depIdxs = []int32{
	1,  // 0: media.UploadImageRequest.visibility:type_name -> media.FileVisibility
	0,  // 1: media.UploadImageRequest.variants:type_name -> media.FileVariant
	0,  // 2: media.GetImageRequest.variant:type_name -> media.FileVariant
	9,  // 3: media.GetImagesRequest.img_ids:type_name -> media.ImageIds
	0,  // 4: media.GetImagesRequest.variant:type_name -> media.FileVariant
	2,  // 5: media.FailedId.status:type_name -> media.UploadStatus
	13, // 6: media.GetImagesResponse.download_urls:type_name -> media.GetImagesResponse.DownloadUrlsEntry
	11, // 7: media.GetImagesResponse.failed_ids:type_name -> media.FailedId
	3,  // 8: media.MediaService.UploadImage:input_type -> media.UploadImageRequest
	5,  // 9: media.MediaService.GetImage:input_type -> media.GetImageRequest
	10, // 10: media.MediaService.GetImages:input_type -> media.GetImagesRequest
	7,  // 11: media.MediaService.ValidateUpload:input_type -> media.ValidateUploadRequest
	4,  // 12: media.MediaService.UploadImage:output_type -> media.UploadImageResponse
	6,  // 13: media.MediaService.GetImage:output_type -> media.GetImageResponse
	12, // 14: media.MediaService.GetImages:output_type -> media.GetImagesResponse
	8,  // 15: media.MediaService.ValidateUpload:output_type -> media.ValidateUploadResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_media_proto_init() }
func file_media_proto_init() {
	if File_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_proto_rawDesc), len(file_media_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_media_proto_goTypes,
		DependencyIndexes: file_media_proto_depIdxs,
		EnumInfos:         file_media_proto_enumTypes,
		MessageInfos:      file_media_proto_msgTypes,
	}.Build()
	File_media_proto = out.File
	file_media_proto_goTypes = nil
	file_media_proto_depIdxs = nil
}
