// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: posts.proto

package posts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	common "social-network/shared/gen-go/common"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// generic request message that only includes
// an entity id (can be post, event, comment id, etc)
type SimpleIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleIdReq) Reset() {
	*x = SimpleIdReq{}
	mi := &file_posts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleIdReq) ProtoMessage() {}

func (x *SimpleIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleIdReq.ProtoReflect.Descriptor instead.
func (*SimpleIdReq) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleIdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// generic response message that only includes
// an entity id (can be post, event, comment id, etc)
type IdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdResp) Reset() {
	*x = IdResp{}
	mi := &file_posts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdResp) ProtoMessage() {}

func (x *IdResp) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdResp.ProtoReflect.Descriptor instead.
func (*IdResp) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{1}
}

func (x *IdResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// response message for a post's audience
type AudienceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Audience      string                 `protobuf:"bytes,1,opt,name=audience,proto3" json:"audience,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudienceResp) Reset() {
	*x = AudienceResp{}
	mi := &file_posts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudienceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudienceResp) ProtoMessage() {}

func (x *AudienceResp) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudienceResp.ProtoReflect.Descriptor instead.
func (*AudienceResp) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{2}
}

func (x *AudienceResp) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

// generic request message that includes
// the id of the requesting user
// and an entity id (can be post, comment, event, etc)
type GenericReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   int64                  `protobuf:"varint,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	EntityId      int64                  `protobuf:"varint,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericReq) Reset() {
	*x = GenericReq{}
	mi := &file_posts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericReq) ProtoMessage() {}

func (x *GenericReq) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericReq.ProtoReflect.Descriptor instead.
func (*GenericReq) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{3}
}

func (x *GenericReq) GetRequesterId() int64 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *GenericReq) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

// generic request message that includes
// the id of the requesting user
// an entity id (can be post, comment, event, etc)
// and pagination information
type EntityIdPaginatedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   int64                  `protobuf:"varint,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	EntityId      int64                  `protobuf:"varint,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityIdPaginatedReq) Reset() {
	*x = EntityIdPaginatedReq{}
	mi := &file_posts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityIdPaginatedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityIdPaginatedReq) ProtoMessage() {}

func (x *EntityIdPaginatedReq) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityIdPaginatedReq.ProtoReflect.Descriptor instead.
func (*EntityIdPaginatedReq) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{4}
}

func (x *EntityIdPaginatedReq) GetRequesterId() int64 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *EntityIdPaginatedReq) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntityIdPaginatedReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *EntityIdPaginatedReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// generic request message that includes
// the id of the requesting user
// and pagination information
type GenericPaginatedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   int64                  `protobuf:"varint,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericPaginatedReq) Reset() {
	*x = GenericPaginatedReq{}
	mi := &file_posts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericPaginatedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericPaginatedReq) ProtoMessage() {}

func (x *GenericPaginatedReq) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericPaginatedReq.ProtoReflect.Descriptor instead.
func (*GenericPaginatedReq) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{5}
}

func (x *GenericPaginatedReq) GetRequesterId() int64 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *GenericPaginatedReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GenericPaginatedReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Response message that describes a post
type Post struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	PostId                int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	PostBody              string                 `protobuf:"bytes,2,opt,name=post_body,json=postBody,proto3" json:"post_body,omitempty"`
	User                  *common.User           `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`                       // includes id, username and avatar url
	GroupId               int64                  `protobuf:"varint,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` //can be 0, meaning the post doesn't belong to a group
	Audience              string                 `protobuf:"bytes,5,opt,name=audience,proto3" json:"audience,omitempty"`               // one of "everyone", "followers","selected","group"
	CommentsCount         int32                  `protobuf:"varint,6,opt,name=comments_count,json=commentsCount,proto3" json:"comments_count,omitempty"`
	ReactionsCount        int32                  `protobuf:"varint,7,opt,name=reactions_count,json=reactionsCount,proto3" json:"reactions_count,omitempty"`
	LastCommentedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_commented_at,json=lastCommentedAt,proto3" json:"last_commented_at,omitempty"`
	CreatedAt             *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LikedByUser           bool                   `protobuf:"varint,11,opt,name=liked_by_user,json=likedByUser,proto3" json:"liked_by_user,omitempty"`
	ImageId               int64                  `protobuf:"varint,12,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`                                            //can be 0, meaning no associated image
	ImageUrl              string                 `protobuf:"bytes,13,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`                                          // can be an empty string if image_id is 0
	SelectedAudienceUsers *common.ListUsers      `protobuf:"bytes,14,opt,name=selected_audience_users,json=selectedAudienceUsers,proto3" json:"selected_audience_users,omitempty"` //empty unless audience="selected"
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_posts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{6}
}

func (x *Post) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *Post) GetPostBody() string {
	if x != nil {
		return x.PostBody
	}
	return ""
}

func (x *Post) GetUser() *common.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Post) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *Post) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *Post) GetCommentsCount() int32 {
	if x != nil {
		return x.CommentsCount
	}
	return 0
}

func (x *Post) GetReactionsCount() int32 {
	if x != nil {
		return x.ReactionsCount
	}
	return 0
}

func (x *Post) GetLastCommentedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCommentedAt
	}
	return nil
}

func (x *Post) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Post) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Post) GetLikedByUser() bool {
	if x != nil {
		return x.LikedByUser
	}
	return false
}

func (x *Post) GetImageId() int64 {
	if x != nil {
		return x.ImageId
	}
	return 0
}

func (x *Post) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Post) GetSelectedAudienceUsers() *common.ListUsers {
	if x != nil {
		return x.SelectedAudienceUsers
	}
	return nil
}

// Response message with multiple posts
type ListPosts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*Post                `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPosts) Reset() {
	*x = ListPosts{}
	mi := &file_posts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPosts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPosts) ProtoMessage() {}

func (x *ListPosts) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPosts.ProtoReflect.Descriptor instead.
func (*ListPosts) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{7}
}

func (x *ListPosts) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

// Request message for creating a post
type CreatePostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatorId     int64                  `protobuf:"varint,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	GroupId       int64                  `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`            //can be 0 if audience is not "group"
	Audience      string                 `protobuf:"bytes,4,opt,name=audience,proto3" json:"audience,omitempty"`                          // one of "everyone", "followers","selected","group"
	AudienceIds   *common.UserIds        `protobuf:"bytes,5,opt,name=audience_ids,json=audienceIds,proto3" json:"audience_ids,omitempty"` // empty unless audience="selected"
	ImageId       int64                  `protobuf:"varint,6,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`            //can be 0 if no image
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostReq) Reset() {
	*x = CreatePostReq{}
	mi := &file_posts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostReq) ProtoMessage() {}

func (x *CreatePostReq) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostReq.ProtoReflect.Descriptor instead.
func (*CreatePostReq) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{8}
}

func (x *CreatePostReq) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *CreatePostReq) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *CreatePostReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CreatePostReq) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *CreatePostReq) GetAudienceIds() *common.UserIds {
	if x != nil {
		return x.AudienceIds
	}
	return nil
}

func (x *CreatePostReq) GetImageId() int64 {
	if x != nil {
		return x.ImageId
	}
	return 0
}

// Request message for editing a post
type EditPostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   int64                  `protobuf:"varint,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	PostId        int64                  `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	ImageId       int64                  `protobuf:"varint,4,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`             //can be 0 if no image
	Audience      string                 `protobuf:"bytes,5,opt,name=audience,proto3" json:"audience,omitempty"`                           // one of "everyone", "followers","selected","group"
	AudienceIds   *common.UserIds        `protobuf:"bytes,6,opt,name=audience_ids,json=audienceIds,proto3" json:"audience_ids,omitempty"`  //empty unless audience="selected"
	DeleteImage   bool                   `protobuf:"varint,7,opt,name=delete_image,json=deleteImage,proto3" json:"delete_image,omitempty"` //true if removing preexisting image
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditPostReq) Reset() {
	*x = EditPostReq{}
	mi := &file_posts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditPostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditPostReq) ProtoMessage() {}

func (x *EditPostReq) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditPostReq.ProtoReflect.Descriptor instead.
func (*EditPostReq) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{9}
}

func (x *EditPostReq) GetRequesterId() int64 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *EditPostReq) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *EditPostReq) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *EditPostReq) GetImageId() int64 {
	if x != nil {
		return x.ImageId
	}
	return 0
}

func (x *EditPostReq) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *EditPostReq) GetAudienceIds() *common.UserIds {
	if x != nil {
		return x.AudienceIds
	}
	return nil
}

func (x *EditPostReq) GetDeleteImage() bool {
	if x != nil {
		return x.DeleteImage
	}
	return false
}

// Request message for retrieving a user's posts
type GetUserPostsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatorId     int64                  `protobuf:"varint,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	RequesterId   int64                  `protobuf:"varint,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPostsReq) Reset() {
	*x = GetUserPostsReq{}
	mi := &file_posts_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPostsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPostsReq) ProtoMessage() {}

func (x *GetUserPostsReq) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPostsReq.ProtoReflect.Descriptor instead.
func (*GetUserPostsReq) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserPostsReq) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *GetUserPostsReq) GetRequesterId() int64 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *GetUserPostsReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUserPostsReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Request message for retrieving the personalized feed
// (posts by followers with restricted visibility that requester is allowed to view)
type GetPersonalizedFeedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   int64                  `protobuf:"varint,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPersonalizedFeedReq) Reset() {
	*x = GetPersonalizedFeedReq{}
	mi := &file_posts_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPersonalizedFeedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonalizedFeedReq) ProtoMessage() {}

func (x *GetPersonalizedFeedReq) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonalizedFeedReq.ProtoReflect.Descriptor instead.
func (*GetPersonalizedFeedReq) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{11}
}

func (x *GetPersonalizedFeedReq) GetRequesterId() int64 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *GetPersonalizedFeedReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetPersonalizedFeedReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Request message for retrieving posts belonging to a group
type GetGroupPostsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   int64                  `protobuf:"varint,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupPostsReq) Reset() {
	*x = GetGroupPostsReq{}
	mi := &file_posts_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupPostsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupPostsReq) ProtoMessage() {}

func (x *GetGroupPostsReq) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupPostsReq.ProtoReflect.Descriptor instead.
func (*GetGroupPostsReq) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{12}
}

func (x *GetGroupPostsReq) GetRequesterId() int64 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *GetGroupPostsReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GetGroupPostsReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetGroupPostsReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Response message that describes a comment
type Comment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CommentId      int64                  `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	ParentId       int64                  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Body           string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	User           *common.User           `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"` // includes id, username and avatar url
	ReactionsCount int32                  `protobuf:"varint,5,opt,name=reactions_count,json=reactionsCount,proto3" json:"reactions_count,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LikedByUser    bool                   `protobuf:"varint,8,opt,name=liked_by_user,json=likedByUser,proto3" json:"liked_by_user,omitempty"`
	ImageId        int64                  `protobuf:"varint,9,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`    // can be 0 if no image
	ImageUrl       string                 `protobuf:"bytes,10,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"` // can be empty string if image id=0
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_posts_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{13}
}

func (x *Comment) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *Comment) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Comment) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Comment) GetUser() *common.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Comment) GetReactionsCount() int32 {
	if x != nil {
		return x.ReactionsCount
	}
	return 0
}

func (x *Comment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Comment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Comment) GetLikedByUser() bool {
	if x != nil {
		return x.LikedByUser
	}
	return false
}

func (x *Comment) GetImageId() int64 {
	if x != nil {
		return x.ImageId
	}
	return 0
}

func (x *Comment) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

// Response message with multiple comments
type ListComments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*Comment             `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListComments) Reset() {
	*x = ListComments{}
	mi := &file_posts_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListComments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListComments) ProtoMessage() {}

func (x *ListComments) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListComments.ProtoReflect.Descriptor instead.
func (*ListComments) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{14}
}

func (x *ListComments) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

// Request message for creating a comment
type CreateCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatorId     int64                  `protobuf:"varint,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	ParentId      int64                  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	ImageId       int64                  `protobuf:"varint,4,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"` //can be 0 if no image
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentReq) Reset() {
	*x = CreateCommentReq{}
	mi := &file_posts_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentReq) ProtoMessage() {}

func (x *CreateCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentReq.ProtoReflect.Descriptor instead.
func (*CreateCommentReq) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{15}
}

func (x *CreateCommentReq) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *CreateCommentReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CreateCommentReq) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *CreateCommentReq) GetImageId() int64 {
	if x != nil {
		return x.ImageId
	}
	return 0
}

// Request message for editing a comment
type EditCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatorId     int64                  `protobuf:"varint,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	CommentId     int64                  `protobuf:"varint,2,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	ImageId       int64                  `protobuf:"varint,4,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`             //can be 0 if no image
	DeleteImage   bool                   `protobuf:"varint,5,opt,name=delete_image,json=deleteImage,proto3" json:"delete_image,omitempty"` //true if removing preexisting image
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditCommentReq) Reset() {
	*x = EditCommentReq{}
	mi := &file_posts_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCommentReq) ProtoMessage() {}

func (x *EditCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCommentReq.ProtoReflect.Descriptor instead.
func (*EditCommentReq) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{16}
}

func (x *EditCommentReq) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *EditCommentReq) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *EditCommentReq) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *EditCommentReq) GetImageId() int64 {
	if x != nil {
		return x.ImageId
	}
	return 0
}

func (x *EditCommentReq) GetDeleteImage() bool {
	if x != nil {
		return x.DeleteImage
	}
	return false
}

// Response message that describes an event
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	User          *common.User           `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"` // includes id, username and avatar url
	GroupId       int64                  `protobuf:"varint,5,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	EventDate     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=event_date,json=eventDate,proto3" json:"event_date,omitempty"`
	GoingCount    int32                  `protobuf:"varint,7,opt,name=going_count,json=goingCount,proto3" json:"going_count,omitempty"`
	NotGoingCount int32                  `protobuf:"varint,8,opt,name=not_going_count,json=notGoingCount,proto3" json:"not_going_count,omitempty"`
	ImageId       int64                  `protobuf:"varint,9,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`    //can be 0 if no image
	ImageUrl      string                 `protobuf:"bytes,10,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"` //can be empty string if image id=0
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UserResponse  *wrapperspb.BoolValue  `protobuf:"bytes,13,opt,name=user_response,json=userResponse,proto3" json:"user_response,omitempty"` //nil for no response, true for going, false for not going
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_posts_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{17}
}

func (x *Event) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Event) GetUser() *common.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Event) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *Event) GetEventDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EventDate
	}
	return nil
}

func (x *Event) GetGoingCount() int32 {
	if x != nil {
		return x.GoingCount
	}
	return 0
}

func (x *Event) GetNotGoingCount() int32 {
	if x != nil {
		return x.NotGoingCount
	}
	return 0
}

func (x *Event) GetImageId() int64 {
	if x != nil {
		return x.ImageId
	}
	return 0
}

func (x *Event) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Event) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Event) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Event) GetUserResponse() *wrapperspb.BoolValue {
	if x != nil {
		return x.UserResponse
	}
	return nil
}

// Response message with multiple events
type ListEvents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEvents) Reset() {
	*x = ListEvents{}
	mi := &file_posts_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEvents) ProtoMessage() {}

func (x *ListEvents) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEvents.ProtoReflect.Descriptor instead.
func (*ListEvents) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{18}
}

func (x *ListEvents) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

// Request message for creating an event
type CreateEventReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	CreatorId     int64                  `protobuf:"varint,3,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	GroupId       int64                  `protobuf:"varint,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ImageId       int64                  `protobuf:"varint,5,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"` //can be 0 if no image
	EventDate     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=event_date,json=eventDate,proto3" json:"event_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventReq) Reset() {
	*x = CreateEventReq{}
	mi := &file_posts_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventReq) ProtoMessage() {}

func (x *CreateEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventReq.ProtoReflect.Descriptor instead.
func (*CreateEventReq) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{19}
}

func (x *CreateEventReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateEventReq) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *CreateEventReq) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *CreateEventReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CreateEventReq) GetImageId() int64 {
	if x != nil {
		return x.ImageId
	}
	return 0
}

func (x *CreateEventReq) GetEventDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EventDate
	}
	return nil
}

// Request message for editing an event
type EditEventReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	RequesterId   int64                  `protobuf:"varint,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	ImageId       int64                  `protobuf:"varint,5,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"` //can be 0 if no image
	EventDate     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=event_date,json=eventDate,proto3" json:"event_date,omitempty"`
	DeleteImage   bool                   `protobuf:"varint,7,opt,name=delete_image,json=deleteImage,proto3" json:"delete_image,omitempty"` //true if removing preexisting image
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditEventReq) Reset() {
	*x = EditEventReq{}
	mi := &file_posts_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditEventReq) ProtoMessage() {}

func (x *EditEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditEventReq.ProtoReflect.Descriptor instead.
func (*EditEventReq) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{20}
}

func (x *EditEventReq) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *EditEventReq) GetRequesterId() int64 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *EditEventReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EditEventReq) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *EditEventReq) GetImageId() int64 {
	if x != nil {
		return x.ImageId
	}
	return 0
}

func (x *EditEventReq) GetEventDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EventDate
	}
	return nil
}

func (x *EditEventReq) GetDeleteImage() bool {
	if x != nil {
		return x.DeleteImage
	}
	return false
}

// Request message for responding to an event
type RespondToEventReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	ResponderId   int64                  `protobuf:"varint,2,opt,name=responder_id,json=responderId,proto3" json:"responder_id,omitempty"`
	Going         bool                   `protobuf:"varint,3,opt,name=going,proto3" json:"going,omitempty"` //true for going, false for not going
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondToEventReq) Reset() {
	*x = RespondToEventReq{}
	mi := &file_posts_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondToEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondToEventReq) ProtoMessage() {}

func (x *RespondToEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondToEventReq.ProtoReflect.Descriptor instead.
func (*RespondToEventReq) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{21}
}

func (x *RespondToEventReq) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *RespondToEventReq) GetResponderId() int64 {
	if x != nil {
		return x.ResponderId
	}
	return 0
}

func (x *RespondToEventReq) GetGoing() bool {
	if x != nil {
		return x.Going
	}
	return false
}

var File_posts_proto protoreflect.FileDescriptor

const file_posts_proto_rawDesc = "" +
	"\n" +
	"\vposts.proto\x12\x05posts\x1a\fcommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1d\n" +
	"\vSimpleIdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x18\n" +
	"\x06IdResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"*\n" +
	"\fAudienceResp\x12\x1a\n" +
	"\baudience\x18\x01 \x01(\tR\baudience\"L\n" +
	"\n" +
	"GenericReq\x12!\n" +
	"\frequester_id\x18\x01 \x01(\x03R\vrequesterId\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\x03R\bentityId\"\x84\x01\n" +
	"\x14EntityIdPaginatedReq\x12!\n" +
	"\frequester_id\x18\x01 \x01(\x03R\vrequesterId\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\x03R\bentityId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"f\n" +
	"\x13GenericPaginatedReq\x12!\n" +
	"\frequester_id\x18\x01 \x01(\x03R\vrequesterId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\xca\x04\n" +
	"\x04Post\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\x12\x1b\n" +
	"\tpost_body\x18\x02 \x01(\tR\bpostBody\x12 \n" +
	"\x04user\x18\x03 \x01(\v2\f.common.UserR\x04user\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\x03R\agroupId\x12\x1a\n" +
	"\baudience\x18\x05 \x01(\tR\baudience\x12%\n" +
	"\x0ecomments_count\x18\x06 \x01(\x05R\rcommentsCount\x12'\n" +
	"\x0freactions_count\x18\a \x01(\x05R\x0ereactionsCount\x12F\n" +
	"\x11last_commented_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x0flastCommentedAt\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\"\n" +
	"\rliked_by_user\x18\v \x01(\bR\vlikedByUser\x12\x19\n" +
	"\bimage_id\x18\f \x01(\x03R\aimageId\x12\x1b\n" +
	"\timage_url\x18\r \x01(\tR\bimageUrl\x12I\n" +
	"\x17selected_audience_users\x18\x0e \x01(\v2\x11.common.ListUsersR\x15selectedAudienceUsers\".\n" +
	"\tListPosts\x12!\n" +
	"\x05posts\x18\x01 \x03(\v2\v.posts.PostR\x05posts\"\xc8\x01\n" +
	"\rCreatePostReq\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x01 \x01(\x03R\tcreatorId\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\x03R\agroupId\x12\x1a\n" +
	"\baudience\x18\x04 \x01(\tR\baudience\x122\n" +
	"\faudience_ids\x18\x05 \x01(\v2\x0f.common.UserIdsR\vaudienceIds\x12\x19\n" +
	"\bimage_id\x18\x06 \x01(\x03R\aimageId\"\xeb\x01\n" +
	"\vEditPostReq\x12!\n" +
	"\frequester_id\x18\x01 \x01(\x03R\vrequesterId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x03R\x06postId\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x19\n" +
	"\bimage_id\x18\x04 \x01(\x03R\aimageId\x12\x1a\n" +
	"\baudience\x18\x05 \x01(\tR\baudience\x122\n" +
	"\faudience_ids\x18\x06 \x01(\v2\x0f.common.UserIdsR\vaudienceIds\x12!\n" +
	"\fdelete_image\x18\a \x01(\bR\vdeleteImage\"\x81\x01\n" +
	"\x0fGetUserPostsReq\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x01 \x01(\x03R\tcreatorId\x12!\n" +
	"\frequester_id\x18\x02 \x01(\x03R\vrequesterId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"i\n" +
	"\x16GetPersonalizedFeedReq\x12!\n" +
	"\frequester_id\x18\x01 \x01(\x03R\vrequesterId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"~\n" +
	"\x10GetGroupPostsReq\x12!\n" +
	"\frequester_id\x18\x01 \x01(\x03R\vrequesterId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\xf6\x02\n" +
	"\aComment\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x03R\tcommentId\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x03R\bparentId\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12 \n" +
	"\x04user\x18\x04 \x01(\v2\f.common.UserR\x04user\x12'\n" +
	"\x0freactions_count\x18\x05 \x01(\x05R\x0ereactionsCount\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\"\n" +
	"\rliked_by_user\x18\b \x01(\bR\vlikedByUser\x12\x19\n" +
	"\bimage_id\x18\t \x01(\x03R\aimageId\x12\x1b\n" +
	"\timage_url\x18\n" +
	" \x01(\tR\bimageUrl\":\n" +
	"\fListComments\x12*\n" +
	"\bcomments\x18\x01 \x03(\v2\x0e.posts.CommentR\bcomments\"}\n" +
	"\x10CreateCommentReq\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x01 \x01(\x03R\tcreatorId\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x03R\bparentId\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x19\n" +
	"\bimage_id\x18\x04 \x01(\x03R\aimageId\"\xa0\x01\n" +
	"\x0eEditCommentReq\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x01 \x01(\x03R\tcreatorId\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x02 \x01(\x03R\tcommentId\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x19\n" +
	"\bimage_id\x18\x04 \x01(\x03R\aimageId\x12!\n" +
	"\fdelete_image\x18\x05 \x01(\bR\vdeleteImage\"\xfc\x03\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12 \n" +
	"\x04user\x18\x04 \x01(\v2\f.common.UserR\x04user\x12\x19\n" +
	"\bgroup_id\x18\x05 \x01(\x03R\agroupId\x129\n" +
	"\n" +
	"event_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\teventDate\x12\x1f\n" +
	"\vgoing_count\x18\a \x01(\x05R\n" +
	"goingCount\x12&\n" +
	"\x0fnot_going_count\x18\b \x01(\x05R\rnotGoingCount\x12\x19\n" +
	"\bimage_id\x18\t \x01(\x03R\aimageId\x12\x1b\n" +
	"\timage_url\x18\n" +
	" \x01(\tR\bimageUrl\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12?\n" +
	"\ruser_response\x18\r \x01(\v2\x1a.google.protobuf.BoolValueR\fuserResponse\"2\n" +
	"\n" +
	"ListEvents\x12$\n" +
	"\x06events\x18\x01 \x03(\v2\f.posts.EventR\x06events\"\xca\x01\n" +
	"\x0eCreateEventReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x03 \x01(\x03R\tcreatorId\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\x03R\agroupId\x12\x19\n" +
	"\bimage_id\x18\x05 \x01(\x03R\aimageId\x129\n" +
	"\n" +
	"event_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\teventDate\"\xef\x01\n" +
	"\fEditEventReq\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12!\n" +
	"\frequester_id\x18\x02 \x01(\x03R\vrequesterId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x19\n" +
	"\bimage_id\x18\x05 \x01(\x03R\aimageId\x129\n" +
	"\n" +
	"event_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\teventDate\x12!\n" +
	"\fdelete_image\x18\a \x01(\bR\vdeleteImage\"g\n" +
	"\x11RespondToEventReq\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12!\n" +
	"\fresponder_id\x18\x02 \x01(\x03R\vresponderId\x12\x14\n" +
	"\x05going\x18\x03 \x01(\bR\x05going2\xae\v\n" +
	"\fPostsService\x12-\n" +
	"\vGetPostById\x12\x11.posts.GenericReq\x1a\v.posts.Post\x121\n" +
	"\n" +
	"CreatePost\x12\x14.posts.CreatePostReq\x1a\r.posts.IdResp\x127\n" +
	"\n" +
	"DeletePost\x12\x11.posts.GenericReq\x1a\x16.google.protobuf.Empty\x126\n" +
	"\bEditPost\x12\x12.posts.EditPostReq\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\x19GetMostPopularPostInGroup\x12\x12.posts.SimpleIdReq\x1a\v.posts.Post\x12F\n" +
	"\x13GetPersonalizedFeed\x12\x1d.posts.GetPersonalizedFeedReq\x1a\x10.posts.ListPosts\x12=\n" +
	"\rGetPublicFeed\x12\x1a.posts.GenericPaginatedReq\x1a\x10.posts.ListPosts\x12A\n" +
	"\x15GetUserPostsPaginated\x12\x16.posts.GetUserPostsReq\x1a\x10.posts.ListPosts\x12C\n" +
	"\x16GetGroupPostsPaginated\x12\x17.posts.GetGroupPostsReq\x1a\x10.posts.ListPosts\x127\n" +
	"\rCreateComment\x12\x17.posts.CreateCommentReq\x1a\r.posts.IdResp\x12<\n" +
	"\vEditComment\x12\x15.posts.EditCommentReq\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\rDeleteComment\x12\x11.posts.GenericReq\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\x15GetCommentsByParentId\x12\x1b.posts.EntityIdPaginatedReq\x1a\x13.posts.ListComments\x12D\n" +
	"\x19GetPostAudienceForComment\x12\x12.posts.SimpleIdReq\x1a\x13.posts.AudienceResp\x123\n" +
	"\vCreateEvent\x12\x15.posts.CreateEventReq\x1a\r.posts.IdResp\x128\n" +
	"\vDeleteEvent\x12\x11.posts.GenericReq\x1a\x16.google.protobuf.Empty\x128\n" +
	"\tEditEvent\x12\x13.posts.EditEventReq\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\x12GetEventsByGroupId\x12\x1b.posts.EntityIdPaginatedReq\x1a\x11.posts.ListEvents\x12B\n" +
	"\x0eRespondToEvent\x12\x18.posts.RespondToEventReq\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\x13RemoveEventResponse\x12\x11.posts.GenericReq\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\x1aSuggestUsersByPostActivity\x12\x12.posts.SimpleIdReq\x1a\x11.common.ListUsers\x12C\n" +
	"\x16ToggleOrInsertReaction\x12\x11.posts.GenericReq\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\x13GetWhoLikedEntityId\x12\x11.posts.GenericReq\x1a\x11.common.ListUsersB*Z(social-network/shared/gen-go/posts;postsb\x06proto3"

var (
	file_posts_proto_rawDescOnce sync.Once
	file_posts_proto_rawDescData []byte
)

func file_posts_proto_rawDescGZIP() []byte {
	file_posts_proto_rawDescOnce.Do(func() {
		file_posts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_posts_proto_rawDesc), len(file_posts_proto_rawDesc)))
	})
	return file_posts_proto_rawDescData
}

var file_posts_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_posts_proto_goTypes = []any{
	(*SimpleIdReq)(nil),            // 0: posts.SimpleIdReq
	(*IdResp)(nil),                 // 1: posts.IdResp
	(*AudienceResp)(nil),           // 2: posts.AudienceResp
	(*GenericReq)(nil),             // 3: posts.GenericReq
	(*EntityIdPaginatedReq)(nil),   // 4: posts.EntityIdPaginatedReq
	(*GenericPaginatedReq)(nil),    // 5: posts.GenericPaginatedReq
	(*Post)(nil),                   // 6: posts.Post
	(*ListPosts)(nil),              // 7: posts.ListPosts
	(*CreatePostReq)(nil),          // 8: posts.CreatePostReq
	(*EditPostReq)(nil),            // 9: posts.EditPostReq
	(*GetUserPostsReq)(nil),        // 10: posts.GetUserPostsReq
	(*GetPersonalizedFeedReq)(nil), // 11: posts.GetPersonalizedFeedReq
	(*GetGroupPostsReq)(nil),       // 12: posts.GetGroupPostsReq
	(*Comment)(nil),                // 13: posts.Comment
	(*ListComments)(nil),           // 14: posts.ListComments
	(*CreateCommentReq)(nil),       // 15: posts.CreateCommentReq
	(*EditCommentReq)(nil),         // 16: posts.EditCommentReq
	(*Event)(nil),                  // 17: posts.Event
	(*ListEvents)(nil),             // 18: posts.ListEvents
	(*CreateEventReq)(nil),         // 19: posts.CreateEventReq
	(*EditEventReq)(nil),           // 20: posts.EditEventReq
	(*RespondToEventReq)(nil),      // 21: posts.RespondToEventReq
	(*common.User)(nil),            // 22: common.User
	(*timestamppb.Timestamp)(nil),  // 23: google.protobuf.Timestamp
	(*common.ListUsers)(nil),       // 24: common.ListUsers
	(*common.UserIds)(nil),         // 25: common.UserIds
	(*wrapperspb.BoolValue)(nil),   // 26: google.protobuf.BoolValue
	(*emptypb.Empty)(nil),          // 27: google.protobuf.Empty
}
var file_posts_proto_depIdxs = []int32{
	22, // 0: posts.Post.user:type_name -> common.User
	23, // 1: posts.Post.last_commented_at:type_name -> google.protobuf.Timestamp
	23, // 2: posts.Post.created_at:type_name -> google.protobuf.Timestamp
	23, // 3: posts.Post.updated_at:type_name -> google.protobuf.Timestamp
	24, // 4: posts.Post.selected_audience_users:type_name -> common.ListUsers
	6,  // 5: posts.ListPosts.posts:type_name -> posts.Post
	25, // 6: posts.CreatePostReq.audience_ids:type_name -> common.UserIds
	25, // 7: posts.EditPostReq.audience_ids:type_name -> common.UserIds
	22, // 8: posts.Comment.user:type_name -> common.User
	23, // 9: posts.Comment.created_at:type_name -> google.protobuf.Timestamp
	23, // 10: posts.Comment.updated_at:type_name -> google.protobuf.Timestamp
	13, // 11: posts.ListComments.comments:type_name -> posts.Comment
	22, // 12: posts.Event.user:type_name -> common.User
	23, // 13: posts.Event.event_date:type_name -> google.protobuf.Timestamp
	23, // 14: posts.Event.created_at:type_name -> google.protobuf.Timestamp
	23, // 15: posts.Event.updated_at:type_name -> google.protobuf.Timestamp
	26, // 16: posts.Event.user_response:type_name -> google.protobuf.BoolValue
	17, // 17: posts.ListEvents.events:type_name -> posts.Event
	23, // 18: posts.CreateEventReq.event_date:type_name -> google.protobuf.Timestamp
	23, // 19: posts.EditEventReq.event_date:type_name -> google.protobuf.Timestamp
	3,  // 20: posts.PostsService.GetPostById:input_type -> posts.GenericReq
	8,  // 21: posts.PostsService.CreatePost:input_type -> posts.CreatePostReq
	3,  // 22: posts.PostsService.DeletePost:input_type -> posts.GenericReq
	9,  // 23: posts.PostsService.EditPost:input_type -> posts.EditPostReq
	0,  // 24: posts.PostsService.GetMostPopularPostInGroup:input_type -> posts.SimpleIdReq
	11, // 25: posts.PostsService.GetPersonalizedFeed:input_type -> posts.GetPersonalizedFeedReq
	5,  // 26: posts.PostsService.GetPublicFeed:input_type -> posts.GenericPaginatedReq
	10, // 27: posts.PostsService.GetUserPostsPaginated:input_type -> posts.GetUserPostsReq
	12, // 28: posts.PostsService.GetGroupPostsPaginated:input_type -> posts.GetGroupPostsReq
	15, // 29: posts.PostsService.CreateComment:input_type -> posts.CreateCommentReq
	16, // 30: posts.PostsService.EditComment:input_type -> posts.EditCommentReq
	3,  // 31: posts.PostsService.DeleteComment:input_type -> posts.GenericReq
	4,  // 32: posts.PostsService.GetCommentsByParentId:input_type -> posts.EntityIdPaginatedReq
	0,  // 33: posts.PostsService.GetPostAudienceForComment:input_type -> posts.SimpleIdReq
	19, // 34: posts.PostsService.CreateEvent:input_type -> posts.CreateEventReq
	3,  // 35: posts.PostsService.DeleteEvent:input_type -> posts.GenericReq
	20, // 36: posts.PostsService.EditEvent:input_type -> posts.EditEventReq
	4,  // 37: posts.PostsService.GetEventsByGroupId:input_type -> posts.EntityIdPaginatedReq
	21, // 38: posts.PostsService.RespondToEvent:input_type -> posts.RespondToEventReq
	3,  // 39: posts.PostsService.RemoveEventResponse:input_type -> posts.GenericReq
	0,  // 40: posts.PostsService.SuggestUsersByPostActivity:input_type -> posts.SimpleIdReq
	3,  // 41: posts.PostsService.ToggleOrInsertReaction:input_type -> posts.GenericReq
	3,  // 42: posts.PostsService.GetWhoLikedEntityId:input_type -> posts.GenericReq
	6,  // 43: posts.PostsService.GetPostById:output_type -> posts.Post
	1,  // 44: posts.PostsService.CreatePost:output_type -> posts.IdResp
	27, // 45: posts.PostsService.DeletePost:output_type -> google.protobuf.Empty
	27, // 46: posts.PostsService.EditPost:output_type -> google.protobuf.Empty
	6,  // 47: posts.PostsService.GetMostPopularPostInGroup:output_type -> posts.Post
	7,  // 48: posts.PostsService.GetPersonalizedFeed:output_type -> posts.ListPosts
	7,  // 49: posts.PostsService.GetPublicFeed:output_type -> posts.ListPosts
	7,  // 50: posts.PostsService.GetUserPostsPaginated:output_type -> posts.ListPosts
	7,  // 51: posts.PostsService.GetGroupPostsPaginated:output_type -> posts.ListPosts
	1,  // 52: posts.PostsService.CreateComment:output_type -> posts.IdResp
	27, // 53: posts.PostsService.EditComment:output_type -> google.protobuf.Empty
	27, // 54: posts.PostsService.DeleteComment:output_type -> google.protobuf.Empty
	14, // 55: posts.PostsService.GetCommentsByParentId:output_type -> posts.ListComments
	2,  // 56: posts.PostsService.GetPostAudienceForComment:output_type -> posts.AudienceResp
	1,  // 57: posts.PostsService.CreateEvent:output_type -> posts.IdResp
	27, // 58: posts.PostsService.DeleteEvent:output_type -> google.protobuf.Empty
	27, // 59: posts.PostsService.EditEvent:output_type -> google.protobuf.Empty
	18, // 60: posts.PostsService.GetEventsByGroupId:output_type -> posts.ListEvents
	27, // 61: posts.PostsService.RespondToEvent:output_type -> google.protobuf.Empty
	27, // 62: posts.PostsService.RemoveEventResponse:output_type -> google.protobuf.Empty
	24, // 63: posts.PostsService.SuggestUsersByPostActivity:output_type -> common.ListUsers
	27, // 64: posts.PostsService.ToggleOrInsertReaction:output_type -> google.protobuf.Empty
	24, // 65: posts.PostsService.GetWhoLikedEntityId:output_type -> common.ListUsers
	43, // [43:66] is the sub-list for method output_type
	20, // [20:43] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_posts_proto_init() }
func file_posts_proto_init() {
	if File_posts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_posts_proto_rawDesc), len(file_posts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_posts_proto_goTypes,
		DependencyIndexes: file_posts_proto_depIdxs,
		MessageInfos:      file_posts_proto_msgTypes,
	}.Build()
	File_posts_proto = out.File
	file_posts_proto_goTypes = nil
	file_posts_proto_depIdxs = nil
}
