// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: notifications.proto

package notifications

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotificationService_CreateNotification_FullMethodName                = "/notifications.NotificationService/CreateNotification"
	NotificationService_CreateNotifications_FullMethodName               = "/notifications.NotificationService/CreateNotifications"
	NotificationService_CreateFollowRequest_FullMethodName               = "/notifications.NotificationService/CreateFollowRequest"
	NotificationService_CreateNewFollower_FullMethodName                 = "/notifications.NotificationService/CreateNewFollower"
	NotificationService_CreateGroupInvite_FullMethodName                 = "/notifications.NotificationService/CreateGroupInvite"
	NotificationService_CreateGroupInviteForMultipleUsers_FullMethodName = "/notifications.NotificationService/CreateGroupInviteForMultipleUsers"
	NotificationService_CreateGroupJoinRequest_FullMethodName            = "/notifications.NotificationService/CreateGroupJoinRequest"
	NotificationService_CreateNewEvent_FullMethodName                    = "/notifications.NotificationService/CreateNewEvent"
	NotificationService_CreateNewEventForMultipleUsers_FullMethodName    = "/notifications.NotificationService/CreateNewEventForMultipleUsers"
	NotificationService_CreatePostLike_FullMethodName                    = "/notifications.NotificationService/CreatePostLike"
	NotificationService_CreatePostComment_FullMethodName                 = "/notifications.NotificationService/CreatePostComment"
	NotificationService_CreateMention_FullMethodName                     = "/notifications.NotificationService/CreateMention"
	NotificationService_CreateNewMessage_FullMethodName                  = "/notifications.NotificationService/CreateNewMessage"
	NotificationService_CreateNewMessageForMultipleUsers_FullMethodName  = "/notifications.NotificationService/CreateNewMessageForMultipleUsers"
	NotificationService_CreateFollowRequestAccepted_FullMethodName       = "/notifications.NotificationService/CreateFollowRequestAccepted"
	NotificationService_CreateFollowRequestRejected_FullMethodName       = "/notifications.NotificationService/CreateFollowRequestRejected"
	NotificationService_CreateGroupInviteAccepted_FullMethodName         = "/notifications.NotificationService/CreateGroupInviteAccepted"
	NotificationService_CreateGroupInviteRejected_FullMethodName         = "/notifications.NotificationService/CreateGroupInviteRejected"
	NotificationService_CreateGroupJoinRequestAccepted_FullMethodName    = "/notifications.NotificationService/CreateGroupJoinRequestAccepted"
	NotificationService_CreateGroupJoinRequestRejected_FullMethodName    = "/notifications.NotificationService/CreateGroupJoinRequestRejected"
	NotificationService_GetUserNotifications_FullMethodName              = "/notifications.NotificationService/GetUserNotifications"
	NotificationService_GetUnreadNotificationsCount_FullMethodName       = "/notifications.NotificationService/GetUnreadNotificationsCount"
	NotificationService_MarkNotificationAsRead_FullMethodName            = "/notifications.NotificationService/MarkNotificationAsRead"
	NotificationService_MarkNotificationAsActed_FullMethodName           = "/notifications.NotificationService/MarkNotificationAsActed"
	NotificationService_MarkAllAsRead_FullMethodName                     = "/notifications.NotificationService/MarkAllAsRead"
	NotificationService_DeleteNotification_FullMethodName                = "/notifications.NotificationService/DeleteNotification"
	NotificationService_GetNotificationPreferences_FullMethodName        = "/notifications.NotificationService/GetNotificationPreferences"
	NotificationService_UpdateNotificationPreferences_FullMethodName     = "/notifications.NotificationService/UpdateNotificationPreferences"
)

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NotificationService manages creation, retrieval, and updates of notifications.
// Current behavior: INVALID_ARGUMENT for zero ids; INTERNAL for all other failures.
// Desired (not yet implemented): PERMISSION_DENIED for ownership issues; NOT_FOUND for missing notifications/users; UNAUTHENTICATED where auth is required.
type NotificationServiceClient interface {
	// Create notifications
	// Creates a single notification for a user.
	// Returns Error: INVALID_ARGUMENT when user_id is zero; INTERNAL otherwise. Desired: NOT_FOUND for missing user.
	CreateNotification(ctx context.Context, in *CreateNotificationRequest, opts ...grpc.CallOption) (*Notification, error)
	// Creates multiple notifications in bulk.
	// Returns Error: INTERNAL for failures. Desired: INVALID_ARGUMENT per entry, NOT_FOUND for missing users.
	CreateNotifications(ctx context.Context, in *CreateNotificationsRequest, opts ...grpc.CallOption) (*CreateNotificationsResponse, error)
	// Specific notification creation methods
	// Creates a follow request notification
	CreateFollowRequest(ctx context.Context, in *CreateFollowRequestRequest, opts ...grpc.CallOption) (*Notification, error)
	// Creates a new follower notification
	CreateNewFollower(ctx context.Context, in *CreateNewFollowerRequest, opts ...grpc.CallOption) (*Notification, error)
	// Creates a group invite notification
	CreateGroupInvite(ctx context.Context, in *CreateGroupInviteRequest, opts ...grpc.CallOption) (*Notification, error)
	// Creates a group invite notification for multiple users
	CreateGroupInviteForMultipleUsers(ctx context.Context, in *CreateGroupInviteForMultipleUsersRequest, opts ...grpc.CallOption) (*CreateGroupInviteForMultipleUsersResponse, error)
	// Creates a group join request notification
	CreateGroupJoinRequest(ctx context.Context, in *CreateGroupJoinRequestRequest, opts ...grpc.CallOption) (*Notification, error)
	// Creates a new event notification
	CreateNewEvent(ctx context.Context, in *CreateNewEventRequest, opts ...grpc.CallOption) (*Notification, error)
	// Creates a new event notification for multiple users
	CreateNewEventForMultipleUsers(ctx context.Context, in *CreateNewEventForMultipleUsersRequest, opts ...grpc.CallOption) (*CreateNewEventForMultipleUsersResponse, error)
	// Creates a post like notification
	CreatePostLike(ctx context.Context, in *CreatePostLikeRequest, opts ...grpc.CallOption) (*Notification, error)
	// Creates a post comment notification
	CreatePostComment(ctx context.Context, in *CreatePostCommentRequest, opts ...grpc.CallOption) (*Notification, error)
	// Creates a mention notification
	CreateMention(ctx context.Context, in *CreateMentionRequest, opts ...grpc.CallOption) (*Notification, error)
	// Creates a new message notification
	CreateNewMessage(ctx context.Context, in *CreateNewMessageRequest, opts ...grpc.CallOption) (*Notification, error)
	// Creates a new message notification for multiple users
	CreateNewMessageForMultipleUsers(ctx context.Context, in *CreateNewMessageForMultipleUsersRequest, opts ...grpc.CallOption) (*CreateNewMessageForMultipleUsersResponse, error)
	// Creates a follow request accepted notification
	CreateFollowRequestAccepted(ctx context.Context, in *CreateFollowRequestAcceptedRequest, opts ...grpc.CallOption) (*Notification, error)
	// Creates a follow request rejected notification
	CreateFollowRequestRejected(ctx context.Context, in *CreateFollowRequestRejectedRequest, opts ...grpc.CallOption) (*Notification, error)
	// Creates a group invite accepted notification
	CreateGroupInviteAccepted(ctx context.Context, in *CreateGroupInviteAcceptedRequest, opts ...grpc.CallOption) (*Notification, error)
	// Creates a group invite rejected notification
	CreateGroupInviteRejected(ctx context.Context, in *CreateGroupInviteRejectedRequest, opts ...grpc.CallOption) (*Notification, error)
	// Creates a group join request accepted notification
	CreateGroupJoinRequestAccepted(ctx context.Context, in *CreateGroupJoinRequestAcceptedRequest, opts ...grpc.CallOption) (*Notification, error)
	// Creates a group join request rejected notification
	CreateGroupJoinRequestRejected(ctx context.Context, in *CreateGroupJoinRequestRejectedRequest, opts ...grpc.CallOption) (*Notification, error)
	// Get user notifications
	// Retrieves a user's notifications with optional filtering.
	// Returns Error: INVALID_ARGUMENT when user_id is zero; INTERNAL otherwise. Desired: PERMISSION_DENIED/NOT_FOUND as applicable.
	GetUserNotifications(ctx context.Context, in *GetUserNotificationsRequest, opts ...grpc.CallOption) (*GetUserNotificationsResponse, error)
	// Returns the unread notifications count for a user.
	// Returns Error: INVALID_ARGUMENT when user_id is zero; INTERNAL otherwise. Desired: NOT_FOUND for missing user.
	GetUnreadNotificationsCount(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc.CallOption) (*wrapperspb.Int64Value, error)
	// Update notifications
	// Marks a single notification as read for the owner.
	// Returns Error: INVALID_ARGUMENT when ids are zero; INTERNAL otherwise. Desired: NOT_FOUND and PERMISSION_DENIED as applicable.
	MarkNotificationAsRead(ctx context.Context, in *MarkNotificationAsReadRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Marks a single notification as acted for the owner.
	// Returns Error: INVALID_ARGUMENT when ids are zero; INTERNAL otherwise. Desired: NOT_FOUND and PERMISSION_DENIED as applicable.
	MarkNotificationAsActed(ctx context.Context, in *MarkNotificationAsActedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Marks all notifications as read for the user.
	// Returns Error: INVALID_ARGUMENT when user_id is zero; INTERNAL otherwise. Desired: NOT_FOUND/PERMISSION_DENIED as applicable.
	MarkAllAsRead(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Deletes a single notification for the owner.
	// Returns Error: INVALID_ARGUMENT when ids are zero; INTERNAL otherwise. Desired: NOT_FOUND/PERMISSION_DENIED as applicable.
	DeleteNotification(ctx context.Context, in *DeleteNotificationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Notification preferences
	// Retrieves notification preferences for a user.
	// Returns Error: always returns defaults. Desired: NOT_FOUND/PERMISSION_DENIED when implemented.
	GetNotificationPreferences(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc.CallOption) (*NotificationPreferences, error)
	// Updates notification preferences.
	// Returns Error: always succeeds. Desired: INVALID_ARGUMENT/NOT_FOUND/PERMISSION_DENIED when implemented.
	UpdateNotificationPreferences(ctx context.Context, in *UpdateNotificationPreferencesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) CreateNotification(ctx context.Context, in *CreateNotificationRequest, opts ...grpc.CallOption) (*Notification, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Notification)
	err := c.cc.Invoke(ctx, NotificationService_CreateNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) CreateNotifications(ctx context.Context, in *CreateNotificationsRequest, opts ...grpc.CallOption) (*CreateNotificationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNotificationsResponse)
	err := c.cc.Invoke(ctx, NotificationService_CreateNotifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) CreateFollowRequest(ctx context.Context, in *CreateFollowRequestRequest, opts ...grpc.CallOption) (*Notification, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Notification)
	err := c.cc.Invoke(ctx, NotificationService_CreateFollowRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) CreateNewFollower(ctx context.Context, in *CreateNewFollowerRequest, opts ...grpc.CallOption) (*Notification, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Notification)
	err := c.cc.Invoke(ctx, NotificationService_CreateNewFollower_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) CreateGroupInvite(ctx context.Context, in *CreateGroupInviteRequest, opts ...grpc.CallOption) (*Notification, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Notification)
	err := c.cc.Invoke(ctx, NotificationService_CreateGroupInvite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) CreateGroupInviteForMultipleUsers(ctx context.Context, in *CreateGroupInviteForMultipleUsersRequest, opts ...grpc.CallOption) (*CreateGroupInviteForMultipleUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGroupInviteForMultipleUsersResponse)
	err := c.cc.Invoke(ctx, NotificationService_CreateGroupInviteForMultipleUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) CreateGroupJoinRequest(ctx context.Context, in *CreateGroupJoinRequestRequest, opts ...grpc.CallOption) (*Notification, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Notification)
	err := c.cc.Invoke(ctx, NotificationService_CreateGroupJoinRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) CreateNewEvent(ctx context.Context, in *CreateNewEventRequest, opts ...grpc.CallOption) (*Notification, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Notification)
	err := c.cc.Invoke(ctx, NotificationService_CreateNewEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) CreateNewEventForMultipleUsers(ctx context.Context, in *CreateNewEventForMultipleUsersRequest, opts ...grpc.CallOption) (*CreateNewEventForMultipleUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNewEventForMultipleUsersResponse)
	err := c.cc.Invoke(ctx, NotificationService_CreateNewEventForMultipleUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) CreatePostLike(ctx context.Context, in *CreatePostLikeRequest, opts ...grpc.CallOption) (*Notification, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Notification)
	err := c.cc.Invoke(ctx, NotificationService_CreatePostLike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) CreatePostComment(ctx context.Context, in *CreatePostCommentRequest, opts ...grpc.CallOption) (*Notification, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Notification)
	err := c.cc.Invoke(ctx, NotificationService_CreatePostComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) CreateMention(ctx context.Context, in *CreateMentionRequest, opts ...grpc.CallOption) (*Notification, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Notification)
	err := c.cc.Invoke(ctx, NotificationService_CreateMention_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) CreateNewMessage(ctx context.Context, in *CreateNewMessageRequest, opts ...grpc.CallOption) (*Notification, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Notification)
	err := c.cc.Invoke(ctx, NotificationService_CreateNewMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) CreateNewMessageForMultipleUsers(ctx context.Context, in *CreateNewMessageForMultipleUsersRequest, opts ...grpc.CallOption) (*CreateNewMessageForMultipleUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNewMessageForMultipleUsersResponse)
	err := c.cc.Invoke(ctx, NotificationService_CreateNewMessageForMultipleUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) CreateFollowRequestAccepted(ctx context.Context, in *CreateFollowRequestAcceptedRequest, opts ...grpc.CallOption) (*Notification, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Notification)
	err := c.cc.Invoke(ctx, NotificationService_CreateFollowRequestAccepted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) CreateFollowRequestRejected(ctx context.Context, in *CreateFollowRequestRejectedRequest, opts ...grpc.CallOption) (*Notification, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Notification)
	err := c.cc.Invoke(ctx, NotificationService_CreateFollowRequestRejected_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) CreateGroupInviteAccepted(ctx context.Context, in *CreateGroupInviteAcceptedRequest, opts ...grpc.CallOption) (*Notification, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Notification)
	err := c.cc.Invoke(ctx, NotificationService_CreateGroupInviteAccepted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) CreateGroupInviteRejected(ctx context.Context, in *CreateGroupInviteRejectedRequest, opts ...grpc.CallOption) (*Notification, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Notification)
	err := c.cc.Invoke(ctx, NotificationService_CreateGroupInviteRejected_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) CreateGroupJoinRequestAccepted(ctx context.Context, in *CreateGroupJoinRequestAcceptedRequest, opts ...grpc.CallOption) (*Notification, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Notification)
	err := c.cc.Invoke(ctx, NotificationService_CreateGroupJoinRequestAccepted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) CreateGroupJoinRequestRejected(ctx context.Context, in *CreateGroupJoinRequestRejectedRequest, opts ...grpc.CallOption) (*Notification, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Notification)
	err := c.cc.Invoke(ctx, NotificationService_CreateGroupJoinRequestRejected_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) GetUserNotifications(ctx context.Context, in *GetUserNotificationsRequest, opts ...grpc.CallOption) (*GetUserNotificationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserNotificationsResponse)
	err := c.cc.Invoke(ctx, NotificationService_GetUserNotifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) GetUnreadNotificationsCount(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc.CallOption) (*wrapperspb.Int64Value, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(wrapperspb.Int64Value)
	err := c.cc.Invoke(ctx, NotificationService_GetUnreadNotificationsCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) MarkNotificationAsRead(ctx context.Context, in *MarkNotificationAsReadRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NotificationService_MarkNotificationAsRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) MarkNotificationAsActed(ctx context.Context, in *MarkNotificationAsActedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NotificationService_MarkNotificationAsActed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) MarkAllAsRead(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NotificationService_MarkAllAsRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) DeleteNotification(ctx context.Context, in *DeleteNotificationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NotificationService_DeleteNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) GetNotificationPreferences(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc.CallOption) (*NotificationPreferences, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotificationPreferences)
	err := c.cc.Invoke(ctx, NotificationService_GetNotificationPreferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) UpdateNotificationPreferences(ctx context.Context, in *UpdateNotificationPreferencesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NotificationService_UpdateNotificationPreferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
// All implementations must embed UnimplementedNotificationServiceServer
// for forward compatibility.
//
// NotificationService manages creation, retrieval, and updates of notifications.
// Current behavior: INVALID_ARGUMENT for zero ids; INTERNAL for all other failures.
// Desired (not yet implemented): PERMISSION_DENIED for ownership issues; NOT_FOUND for missing notifications/users; UNAUTHENTICATED where auth is required.
type NotificationServiceServer interface {
	// Create notifications
	// Creates a single notification for a user.
	// Returns Error: INVALID_ARGUMENT when user_id is zero; INTERNAL otherwise. Desired: NOT_FOUND for missing user.
	CreateNotification(context.Context, *CreateNotificationRequest) (*Notification, error)
	// Creates multiple notifications in bulk.
	// Returns Error: INTERNAL for failures. Desired: INVALID_ARGUMENT per entry, NOT_FOUND for missing users.
	CreateNotifications(context.Context, *CreateNotificationsRequest) (*CreateNotificationsResponse, error)
	// Specific notification creation methods
	// Creates a follow request notification
	CreateFollowRequest(context.Context, *CreateFollowRequestRequest) (*Notification, error)
	// Creates a new follower notification
	CreateNewFollower(context.Context, *CreateNewFollowerRequest) (*Notification, error)
	// Creates a group invite notification
	CreateGroupInvite(context.Context, *CreateGroupInviteRequest) (*Notification, error)
	// Creates a group invite notification for multiple users
	CreateGroupInviteForMultipleUsers(context.Context, *CreateGroupInviteForMultipleUsersRequest) (*CreateGroupInviteForMultipleUsersResponse, error)
	// Creates a group join request notification
	CreateGroupJoinRequest(context.Context, *CreateGroupJoinRequestRequest) (*Notification, error)
	// Creates a new event notification
	CreateNewEvent(context.Context, *CreateNewEventRequest) (*Notification, error)
	// Creates a new event notification for multiple users
	CreateNewEventForMultipleUsers(context.Context, *CreateNewEventForMultipleUsersRequest) (*CreateNewEventForMultipleUsersResponse, error)
	// Creates a post like notification
	CreatePostLike(context.Context, *CreatePostLikeRequest) (*Notification, error)
	// Creates a post comment notification
	CreatePostComment(context.Context, *CreatePostCommentRequest) (*Notification, error)
	// Creates a mention notification
	CreateMention(context.Context, *CreateMentionRequest) (*Notification, error)
	// Creates a new message notification
	CreateNewMessage(context.Context, *CreateNewMessageRequest) (*Notification, error)
	// Creates a new message notification for multiple users
	CreateNewMessageForMultipleUsers(context.Context, *CreateNewMessageForMultipleUsersRequest) (*CreateNewMessageForMultipleUsersResponse, error)
	// Creates a follow request accepted notification
	CreateFollowRequestAccepted(context.Context, *CreateFollowRequestAcceptedRequest) (*Notification, error)
	// Creates a follow request rejected notification
	CreateFollowRequestRejected(context.Context, *CreateFollowRequestRejectedRequest) (*Notification, error)
	// Creates a group invite accepted notification
	CreateGroupInviteAccepted(context.Context, *CreateGroupInviteAcceptedRequest) (*Notification, error)
	// Creates a group invite rejected notification
	CreateGroupInviteRejected(context.Context, *CreateGroupInviteRejectedRequest) (*Notification, error)
	// Creates a group join request accepted notification
	CreateGroupJoinRequestAccepted(context.Context, *CreateGroupJoinRequestAcceptedRequest) (*Notification, error)
	// Creates a group join request rejected notification
	CreateGroupJoinRequestRejected(context.Context, *CreateGroupJoinRequestRejectedRequest) (*Notification, error)
	// Get user notifications
	// Retrieves a user's notifications with optional filtering.
	// Returns Error: INVALID_ARGUMENT when user_id is zero; INTERNAL otherwise. Desired: PERMISSION_DENIED/NOT_FOUND as applicable.
	GetUserNotifications(context.Context, *GetUserNotificationsRequest) (*GetUserNotificationsResponse, error)
	// Returns the unread notifications count for a user.
	// Returns Error: INVALID_ARGUMENT when user_id is zero; INTERNAL otherwise. Desired: NOT_FOUND for missing user.
	GetUnreadNotificationsCount(context.Context, *wrapperspb.Int64Value) (*wrapperspb.Int64Value, error)
	// Update notifications
	// Marks a single notification as read for the owner.
	// Returns Error: INVALID_ARGUMENT when ids are zero; INTERNAL otherwise. Desired: NOT_FOUND and PERMISSION_DENIED as applicable.
	MarkNotificationAsRead(context.Context, *MarkNotificationAsReadRequest) (*emptypb.Empty, error)
	// Marks a single notification as acted for the owner.
	// Returns Error: INVALID_ARGUMENT when ids are zero; INTERNAL otherwise. Desired: NOT_FOUND and PERMISSION_DENIED as applicable.
	MarkNotificationAsActed(context.Context, *MarkNotificationAsActedRequest) (*emptypb.Empty, error)
	// Marks all notifications as read for the user.
	// Returns Error: INVALID_ARGUMENT when user_id is zero; INTERNAL otherwise. Desired: NOT_FOUND/PERMISSION_DENIED as applicable.
	MarkAllAsRead(context.Context, *wrapperspb.Int64Value) (*emptypb.Empty, error)
	// Deletes a single notification for the owner.
	// Returns Error: INVALID_ARGUMENT when ids are zero; INTERNAL otherwise. Desired: NOT_FOUND/PERMISSION_DENIED as applicable.
	DeleteNotification(context.Context, *DeleteNotificationRequest) (*emptypb.Empty, error)
	// Notification preferences
	// Retrieves notification preferences for a user.
	// Returns Error: always returns defaults. Desired: NOT_FOUND/PERMISSION_DENIED when implemented.
	GetNotificationPreferences(context.Context, *wrapperspb.Int64Value) (*NotificationPreferences, error)
	// Updates notification preferences.
	// Returns Error: always succeeds. Desired: INVALID_ARGUMENT/NOT_FOUND/PERMISSION_DENIED when implemented.
	UpdateNotificationPreferences(context.Context, *UpdateNotificationPreferencesRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedNotificationServiceServer()
}

// UnimplementedNotificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationServiceServer struct{}

func (UnimplementedNotificationServiceServer) CreateNotification(context.Context, *CreateNotificationRequest) (*Notification, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNotification not implemented")
}
func (UnimplementedNotificationServiceServer) CreateNotifications(context.Context, *CreateNotificationsRequest) (*CreateNotificationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNotifications not implemented")
}
func (UnimplementedNotificationServiceServer) CreateFollowRequest(context.Context, *CreateFollowRequestRequest) (*Notification, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFollowRequest not implemented")
}
func (UnimplementedNotificationServiceServer) CreateNewFollower(context.Context, *CreateNewFollowerRequest) (*Notification, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNewFollower not implemented")
}
func (UnimplementedNotificationServiceServer) CreateGroupInvite(context.Context, *CreateGroupInviteRequest) (*Notification, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroupInvite not implemented")
}
func (UnimplementedNotificationServiceServer) CreateGroupInviteForMultipleUsers(context.Context, *CreateGroupInviteForMultipleUsersRequest) (*CreateGroupInviteForMultipleUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroupInviteForMultipleUsers not implemented")
}
func (UnimplementedNotificationServiceServer) CreateGroupJoinRequest(context.Context, *CreateGroupJoinRequestRequest) (*Notification, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroupJoinRequest not implemented")
}
func (UnimplementedNotificationServiceServer) CreateNewEvent(context.Context, *CreateNewEventRequest) (*Notification, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNewEvent not implemented")
}
func (UnimplementedNotificationServiceServer) CreateNewEventForMultipleUsers(context.Context, *CreateNewEventForMultipleUsersRequest) (*CreateNewEventForMultipleUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNewEventForMultipleUsers not implemented")
}
func (UnimplementedNotificationServiceServer) CreatePostLike(context.Context, *CreatePostLikeRequest) (*Notification, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePostLike not implemented")
}
func (UnimplementedNotificationServiceServer) CreatePostComment(context.Context, *CreatePostCommentRequest) (*Notification, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePostComment not implemented")
}
func (UnimplementedNotificationServiceServer) CreateMention(context.Context, *CreateMentionRequest) (*Notification, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMention not implemented")
}
func (UnimplementedNotificationServiceServer) CreateNewMessage(context.Context, *CreateNewMessageRequest) (*Notification, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNewMessage not implemented")
}
func (UnimplementedNotificationServiceServer) CreateNewMessageForMultipleUsers(context.Context, *CreateNewMessageForMultipleUsersRequest) (*CreateNewMessageForMultipleUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNewMessageForMultipleUsers not implemented")
}
func (UnimplementedNotificationServiceServer) CreateFollowRequestAccepted(context.Context, *CreateFollowRequestAcceptedRequest) (*Notification, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFollowRequestAccepted not implemented")
}
func (UnimplementedNotificationServiceServer) CreateFollowRequestRejected(context.Context, *CreateFollowRequestRejectedRequest) (*Notification, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFollowRequestRejected not implemented")
}
func (UnimplementedNotificationServiceServer) CreateGroupInviteAccepted(context.Context, *CreateGroupInviteAcceptedRequest) (*Notification, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroupInviteAccepted not implemented")
}
func (UnimplementedNotificationServiceServer) CreateGroupInviteRejected(context.Context, *CreateGroupInviteRejectedRequest) (*Notification, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroupInviteRejected not implemented")
}
func (UnimplementedNotificationServiceServer) CreateGroupJoinRequestAccepted(context.Context, *CreateGroupJoinRequestAcceptedRequest) (*Notification, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroupJoinRequestAccepted not implemented")
}
func (UnimplementedNotificationServiceServer) CreateGroupJoinRequestRejected(context.Context, *CreateGroupJoinRequestRejectedRequest) (*Notification, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroupJoinRequestRejected not implemented")
}
func (UnimplementedNotificationServiceServer) GetUserNotifications(context.Context, *GetUserNotificationsRequest) (*GetUserNotificationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserNotifications not implemented")
}
func (UnimplementedNotificationServiceServer) GetUnreadNotificationsCount(context.Context, *wrapperspb.Int64Value) (*wrapperspb.Int64Value, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUnreadNotificationsCount not implemented")
}
func (UnimplementedNotificationServiceServer) MarkNotificationAsRead(context.Context, *MarkNotificationAsReadRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkNotificationAsRead not implemented")
}
func (UnimplementedNotificationServiceServer) MarkNotificationAsActed(context.Context, *MarkNotificationAsActedRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkNotificationAsActed not implemented")
}
func (UnimplementedNotificationServiceServer) MarkAllAsRead(context.Context, *wrapperspb.Int64Value) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkAllAsRead not implemented")
}
func (UnimplementedNotificationServiceServer) DeleteNotification(context.Context, *DeleteNotificationRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNotification not implemented")
}
func (UnimplementedNotificationServiceServer) GetNotificationPreferences(context.Context, *wrapperspb.Int64Value) (*NotificationPreferences, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNotificationPreferences not implemented")
}
func (UnimplementedNotificationServiceServer) UpdateNotificationPreferences(context.Context, *UpdateNotificationPreferencesRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNotificationPreferences not implemented")
}
func (UnimplementedNotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {}
func (UnimplementedNotificationServiceServer) testEmbeddedByValue()                             {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServiceServer will
// result in compilation errors.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	// If the following call panics, it indicates UnimplementedNotificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

func _NotificationService_CreateNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CreateNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateNotification(ctx, req.(*CreateNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_CreateNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CreateNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateNotifications(ctx, req.(*CreateNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_CreateFollowRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFollowRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateFollowRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CreateFollowRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateFollowRequest(ctx, req.(*CreateFollowRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_CreateNewFollower_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewFollowerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateNewFollower(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CreateNewFollower_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateNewFollower(ctx, req.(*CreateNewFollowerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_CreateGroupInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupInviteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateGroupInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CreateGroupInvite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateGroupInvite(ctx, req.(*CreateGroupInviteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_CreateGroupInviteForMultipleUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupInviteForMultipleUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateGroupInviteForMultipleUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CreateGroupInviteForMultipleUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateGroupInviteForMultipleUsers(ctx, req.(*CreateGroupInviteForMultipleUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_CreateGroupJoinRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupJoinRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateGroupJoinRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CreateGroupJoinRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateGroupJoinRequest(ctx, req.(*CreateGroupJoinRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_CreateNewEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateNewEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CreateNewEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateNewEvent(ctx, req.(*CreateNewEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_CreateNewEventForMultipleUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewEventForMultipleUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateNewEventForMultipleUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CreateNewEventForMultipleUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateNewEventForMultipleUsers(ctx, req.(*CreateNewEventForMultipleUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_CreatePostLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostLikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreatePostLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CreatePostLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreatePostLike(ctx, req.(*CreatePostLikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_CreatePostComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreatePostComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CreatePostComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreatePostComment(ctx, req.(*CreatePostCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_CreateMention_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMentionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateMention(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CreateMention_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateMention(ctx, req.(*CreateMentionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_CreateNewMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateNewMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CreateNewMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateNewMessage(ctx, req.(*CreateNewMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_CreateNewMessageForMultipleUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewMessageForMultipleUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateNewMessageForMultipleUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CreateNewMessageForMultipleUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateNewMessageForMultipleUsers(ctx, req.(*CreateNewMessageForMultipleUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_CreateFollowRequestAccepted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFollowRequestAcceptedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateFollowRequestAccepted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CreateFollowRequestAccepted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateFollowRequestAccepted(ctx, req.(*CreateFollowRequestAcceptedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_CreateFollowRequestRejected_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFollowRequestRejectedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateFollowRequestRejected(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CreateFollowRequestRejected_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateFollowRequestRejected(ctx, req.(*CreateFollowRequestRejectedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_CreateGroupInviteAccepted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupInviteAcceptedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateGroupInviteAccepted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CreateGroupInviteAccepted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateGroupInviteAccepted(ctx, req.(*CreateGroupInviteAcceptedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_CreateGroupInviteRejected_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupInviteRejectedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateGroupInviteRejected(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CreateGroupInviteRejected_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateGroupInviteRejected(ctx, req.(*CreateGroupInviteRejectedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_CreateGroupJoinRequestAccepted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupJoinRequestAcceptedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateGroupJoinRequestAccepted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CreateGroupJoinRequestAccepted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateGroupJoinRequestAccepted(ctx, req.(*CreateGroupJoinRequestAcceptedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_CreateGroupJoinRequestRejected_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupJoinRequestRejectedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateGroupJoinRequestRejected(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CreateGroupJoinRequestRejected_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateGroupJoinRequestRejected(ctx, req.(*CreateGroupJoinRequestRejectedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_GetUserNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).GetUserNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_GetUserNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).GetUserNotifications(ctx, req.(*GetUserNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_GetUnreadNotificationsCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.Int64Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).GetUnreadNotificationsCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_GetUnreadNotificationsCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).GetUnreadNotificationsCount(ctx, req.(*wrapperspb.Int64Value))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_MarkNotificationAsRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkNotificationAsReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).MarkNotificationAsRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_MarkNotificationAsRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).MarkNotificationAsRead(ctx, req.(*MarkNotificationAsReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_MarkNotificationAsActed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkNotificationAsActedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).MarkNotificationAsActed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_MarkNotificationAsActed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).MarkNotificationAsActed(ctx, req.(*MarkNotificationAsActedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_MarkAllAsRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.Int64Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).MarkAllAsRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_MarkAllAsRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).MarkAllAsRead(ctx, req.(*wrapperspb.Int64Value))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_DeleteNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).DeleteNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_DeleteNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).DeleteNotification(ctx, req.(*DeleteNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_GetNotificationPreferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.Int64Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).GetNotificationPreferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_GetNotificationPreferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).GetNotificationPreferences(ctx, req.(*wrapperspb.Int64Value))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_UpdateNotificationPreferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNotificationPreferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).UpdateNotificationPreferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_UpdateNotificationPreferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).UpdateNotificationPreferences(ctx, req.(*UpdateNotificationPreferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationService_ServiceDesc is the grpc.ServiceDesc for NotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notifications.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNotification",
			Handler:    _NotificationService_CreateNotification_Handler,
		},
		{
			MethodName: "CreateNotifications",
			Handler:    _NotificationService_CreateNotifications_Handler,
		},
		{
			MethodName: "CreateFollowRequest",
			Handler:    _NotificationService_CreateFollowRequest_Handler,
		},
		{
			MethodName: "CreateNewFollower",
			Handler:    _NotificationService_CreateNewFollower_Handler,
		},
		{
			MethodName: "CreateGroupInvite",
			Handler:    _NotificationService_CreateGroupInvite_Handler,
		},
		{
			MethodName: "CreateGroupInviteForMultipleUsers",
			Handler:    _NotificationService_CreateGroupInviteForMultipleUsers_Handler,
		},
		{
			MethodName: "CreateGroupJoinRequest",
			Handler:    _NotificationService_CreateGroupJoinRequest_Handler,
		},
		{
			MethodName: "CreateNewEvent",
			Handler:    _NotificationService_CreateNewEvent_Handler,
		},
		{
			MethodName: "CreateNewEventForMultipleUsers",
			Handler:    _NotificationService_CreateNewEventForMultipleUsers_Handler,
		},
		{
			MethodName: "CreatePostLike",
			Handler:    _NotificationService_CreatePostLike_Handler,
		},
		{
			MethodName: "CreatePostComment",
			Handler:    _NotificationService_CreatePostComment_Handler,
		},
		{
			MethodName: "CreateMention",
			Handler:    _NotificationService_CreateMention_Handler,
		},
		{
			MethodName: "CreateNewMessage",
			Handler:    _NotificationService_CreateNewMessage_Handler,
		},
		{
			MethodName: "CreateNewMessageForMultipleUsers",
			Handler:    _NotificationService_CreateNewMessageForMultipleUsers_Handler,
		},
		{
			MethodName: "CreateFollowRequestAccepted",
			Handler:    _NotificationService_CreateFollowRequestAccepted_Handler,
		},
		{
			MethodName: "CreateFollowRequestRejected",
			Handler:    _NotificationService_CreateFollowRequestRejected_Handler,
		},
		{
			MethodName: "CreateGroupInviteAccepted",
			Handler:    _NotificationService_CreateGroupInviteAccepted_Handler,
		},
		{
			MethodName: "CreateGroupInviteRejected",
			Handler:    _NotificationService_CreateGroupInviteRejected_Handler,
		},
		{
			MethodName: "CreateGroupJoinRequestAccepted",
			Handler:    _NotificationService_CreateGroupJoinRequestAccepted_Handler,
		},
		{
			MethodName: "CreateGroupJoinRequestRejected",
			Handler:    _NotificationService_CreateGroupJoinRequestRejected_Handler,
		},
		{
			MethodName: "GetUserNotifications",
			Handler:    _NotificationService_GetUserNotifications_Handler,
		},
		{
			MethodName: "GetUnreadNotificationsCount",
			Handler:    _NotificationService_GetUnreadNotificationsCount_Handler,
		},
		{
			MethodName: "MarkNotificationAsRead",
			Handler:    _NotificationService_MarkNotificationAsRead_Handler,
		},
		{
			MethodName: "MarkNotificationAsActed",
			Handler:    _NotificationService_MarkNotificationAsActed_Handler,
		},
		{
			MethodName: "MarkAllAsRead",
			Handler:    _NotificationService_MarkAllAsRead_Handler,
		},
		{
			MethodName: "DeleteNotification",
			Handler:    _NotificationService_DeleteNotification_Handler,
		},
		{
			MethodName: "GetNotificationPreferences",
			Handler:    _NotificationService_GetNotificationPreferences_Handler,
		},
		{
			MethodName: "UpdateNotificationPreferences",
			Handler:    _NotificationService_UpdateNotificationPreferences_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notifications.proto",
}
